import { randomUUID } from "node:crypto";
import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { createDatabaseRuntime,runMigrations,type DatabaseRuntime } from "@ai-crm/database";
import { afterAll,beforeAll,describe,expect,it,vi } from "vitest";
import { createPostgresTaskCenterStore } from "./postgres-store.js";
import { createTaskCenter } from "./service.js";
import type { TaskAudit,TaskAuthorization,TaskCenterStore,TaskLifecycleEvent,TaskSourceCommandRouter } from "./types.js";
import { fingerprint } from "./validation.js";

const urlFile=process.env.TEST_TASK_CENTER_DATABASE_URL_FILE;const suite=describe.skipIf(!urlFile);let runtime:DatabaseRuntime;
const projection=(sourceTaskId:string,overrides:Partial<TaskLifecycleEvent>={}):TaskLifecycleEvent=>({eventId:randomUUID(),sourceType:"workflow",sourceTaskId,sourceVersion:1,occurredAt:"2026-07-26T00:00:00Z",status:"open",deepLink:{appId:"workbench",routeId:"task-detail"},...overrides});

suite("PostgreSQL Task Center store",()=>{beforeAll(async()=>{if(!urlFile)throw new Error("TEST_TASK_CENTER_DATABASE_URL_FILE is required.");const connectionString=(await readFile(resolve(urlFile),"utf8")).trim();await runMigrations(connectionString,resolve(import.meta.dirname,"../../../database/migrations"));await runMigrations(connectionString,resolve(import.meta.dirname,"../migrations"));runtime=createDatabaseRuntime({applicationName:"prc02_integration",connectionString,connectionTimeoutMs:5000,idleTimeoutMs:10000,maxConnections:5,statementTimeoutMs:5000});});afterAll(async()=>runtime.close());
  it("cancels a blocked projection transaction without committing a late projection or receipt",async()=>{if(runtime.abortSignalSupport!==true)return;if(!urlFile)throw new Error("TEST_TASK_CENTER_DATABASE_URL_FILE is required.");const connectionString=(await readFile(resolve(urlFile),"utf8")).trim();const blocker=createDatabaseRuntime({applicationName:"prc02_abort_blocker",connectionString,connectionTimeoutMs:5000,idleTimeoutMs:10000,maxConnections:1,statementTimeoutMs:5000});const sourceTaskId=`task.${randomUUID()}`;const input=projection(sourceTaskId);let releaseLock:()=>void=()=>{};let lockReady:()=>void=()=>{};const ready=new Promise<void>((resolveReady)=>{lockReady=resolveReady;});const held=blocker.withTransaction(async()=>{await blocker.execute("select pg_advisory_xact_lock(hashtextextended($1,0))",[`workflow:${sourceTaskId}`]);lockReady();await new Promise<void>((resolveLock)=>{releaseLock=resolveLock;});});try{await ready;const controller=new AbortController();const started=Date.now();const pending=createPostgresTaskCenterStore(runtime).apply(input,controller.signal);setTimeout(()=>{controller.abort(new Error("synthetic projection deadline"));},100);await expect(pending).rejects.toThrow();expect(Date.now()-started).toBeLessThan(2_000);const persisted=await runtime.execute<{projection_count:number;receipt_count:number}>("select (select count(*)::int from crm_task_center.task_projections where source_type=$1 and source_task_id=$2) projection_count,(select count(*)::int from crm_task_center.projection_events where event_id=$3) receipt_count",[input.sourceType,input.sourceTaskId,input.eventId]);expect(persisted.rows[0]).toEqual({projection_count:0,receipt_count:0});}finally{releaseLock();await held;await blocker.close();}});
  it("atomically deduplicates concurrent and reordered events, protects versions, and repairs drift",async()=>{const store=createPostgresTaskCenterStore(runtime);const base=projection(`task.${randomUUID()}`,{deepLink:{appId:"workbench",routeId:"task-detail"}});const results=await Promise.all([store.apply(base),store.apply(base)]);expect(results.map((item)=>item.status).sort()).toEqual(["applied","duplicate"]);const reordered={deepLink:{routeId:base.deepLink.routeId,appId:base.deepLink.appId},status:base.status,occurredAt:base.occurredAt,sourceVersion:base.sourceVersion,sourceTaskId:base.sourceTaskId,sourceType:base.sourceType,eventId:base.eventId};await expect(store.apply(reordered)).resolves.toMatchObject({status:"duplicate"});await expect(store.apply({...reordered,status:"cancelled"})).rejects.toMatchObject({code:"TASK_COMMAND_CONFLICT"});await store.apply({...base,eventId:randomUUID(),sourceVersion:3,status:"completed"});const stale=await store.apply({...base,eventId:randomUUID(),sourceVersion:2});expect(stale).toMatchObject({status:"stale",projection:{sourceVersion:3,status:"completed"}});await expect(store.reconcile({...base,eventId:randomUUID(),sourceVersion:3,status:"open"})).resolves.toMatchObject({status:"applied",projection:{sourceVersion:3,status:"open"}});});
  it("atomically takes over expired command leases and protects the current owner",async()=>{const store=createPostgresTaskCenterStore(runtime);const idempotencyKey=`idem.${randomUUID()}`;const firstToken="43000000-0000-4000-8000-000000000001";const secondToken="43000000-0000-4000-8000-000000000002";const thirdToken="43000000-0000-4000-8000-000000000003";const commandFingerprint="a".repeat(64);const started=new Date("2026-07-26T00:00:00Z");await expect(store.claimCommand({idempotencyKey,fingerprint:commandFingerprint,leaseToken:firstToken,now:started,leaseExpiresAt:new Date(started.getTime()+1_000)})).resolves.toEqual({status:"claimed",leaseToken:firstToken});await expect(store.claimCommand({idempotencyKey,fingerprint:commandFingerprint,leaseToken:secondToken,now:new Date(started.getTime()+999),leaseExpiresAt:new Date(started.getTime()+1_999)})).resolves.toEqual({status:"running"});await expect(store.claimCommand({idempotencyKey,fingerprint:"b".repeat(64),leaseToken:secondToken,now:new Date(started.getTime()+1_001),leaseExpiresAt:new Date(started.getTime()+2_001)})).rejects.toMatchObject({code:"TASK_COMMAND_CONFLICT"});await expect(store.claimCommand({idempotencyKey,fingerprint:commandFingerprint,leaseToken:secondToken,now:new Date(started.getTime()+1_001),leaseExpiresAt:new Date(started.getTime()+2_001)})).resolves.toEqual({status:"claimed",leaseToken:secondToken});await expect(store.acceptCommand({idempotencyKey,leaseToken:firstToken,result:{sourceCommandId:"command.stale",status:"accepted"}})).resolves.toBe(false);await store.releaseCommand({idempotencyKey,leaseToken:firstToken});await expect(store.claimCommand({idempotencyKey,fingerprint:commandFingerprint,leaseToken:thirdToken,now:new Date(started.getTime()+1_500),leaseExpiresAt:new Date(started.getTime()+2_500)})).resolves.toEqual({status:"running"});await expect(store.acceptCommand({idempotencyKey,leaseToken:secondToken,result:{sourceCommandId:"command.synthetic",status:"accepted"}})).resolves.toBe(true);await expect(store.claimCommand({idempotencyKey,fingerprint:commandFingerprint,leaseToken:thirdToken,now:new Date(started.getTime()+5_000),leaseExpiresAt:new Date(started.getTime()+6_000)})).resolves.toEqual({status:"accepted",result:{sourceCommandId:"command.synthetic",status:"accepted"}});});
  it("recovers real PostgreSQL receipts around source interruption without duplicating source effects",async()=>{const base=createPostgresTaskCenterStore(runtime);let loseFirstReceipt=true;const store:TaskCenterStore={apply:(input)=>base.apply(input),reconcile:(input)=>base.reconcile(input),get:(input)=>base.get(input),list:(input)=>base.list(input),claimCommand:(input)=>base.claimCommand(input),releaseCommand:(input)=>base.releaseCommand(input),acceptCommand:async(input)=>loseFirstReceipt?(loseFirstReceipt=false,false):base.acceptCommand(input)};let clock=Date.parse("2026-07-26T00:00:00Z");let token=10;const effects=new Map<string,{sourceCommandId:string;status:"accepted"}>();const complete=vi.fn((input:{idempotencyKey:string})=>{const result=effects.get(input.idempotencyKey)??{sourceCommandId:`command.${String(effects.size+1)}`,status:"accepted" as const};effects.set(input.idempotencyKey,result);return Promise.resolve(result);});const authorization:TaskAuthorization={authorize:()=>Promise.resolve({allowed:true,decisionId:"decision.synthetic"})};const audit:TaskAudit={record:()=>Promise.resolve()};const service=createTaskCenter({store,authorization,audit,router:{complete} as TaskSourceCommandRouter,sourceReader:{get:()=>Promise.reject(new Error("unused"))},now:()=>clock,commandLeaseMs:1_000,commandLeaseToken:()=>`43000000-0000-4000-8000-${String(token++).padStart(12,"0")}`});const sourceTaskId=`task.${randomUUID()}`;await service.apply(projection(sourceTaskId));const beforeCommand={actor:{principalId:"principal.synthetic"},idempotencyKey:`idem.${randomUUID()}`,sourceType:"workflow",sourceTaskId};await base.claimCommand({idempotencyKey:beforeCommand.idempotencyKey,fingerprint:fingerprint({actor:beforeCommand.actor.principalId,sourceType:beforeCommand.sourceType,sourceTaskId:beforeCommand.sourceTaskId}),leaseToken:"43000000-0000-4000-8000-000000000001",now:new Date(clock),leaseExpiresAt:new Date(clock+1_000)});clock+=1_001;await expect(service.complete(beforeCommand)).rejects.toMatchObject({code:"TASK_COMMAND_IN_PROGRESS",retryable:true});clock+=1_001;await expect(service.complete(beforeCommand)).resolves.toMatchObject({status:"accepted"});const ambiguousCommand={...beforeCommand,idempotencyKey:`idem.${randomUUID()}`};await expect(service.complete(ambiguousCommand)).resolves.toMatchObject({status:"accepted"});await expect(service.complete(ambiguousCommand)).resolves.toMatchObject({status:"accepted"});expect(effects.size).toBe(2);expect(complete).toHaveBeenCalledTimes(3);});
});
