/* eslint-disable @typescript-eslint/unbound-method -- assertions target Vitest function properties, not method invocation. */
import { describe,expect,it,vi } from "vitest";
import { WorkflowError } from "./errors.js";
import { createWorkflowFacade } from "./service.js";
import { createMemoryWorkflowCommandLedger } from "./testing.js";
import type { WorkflowAudit,WorkflowAuthorization,WorkflowEngine,WorkflowLifecycleSink } from "./types.js";

const actor={principalId:"principal-1"};
const definition={definitionId:"syntheticHumanTaskV1:1:definition-1",deploymentId:"deployment-1",key:"syntheticHumanTaskV1",resourceName:"synthetic-human-task.v1.bpmn20.xml",version:1};
const instance={definitionId:definition.definitionId,definitionKey:definition.key,definitionVersion:1,processInstanceId:"instance-1",status:"active" as const};
const task={definitionId:definition.definitionId,processInstanceId:instance.processInstanceId,sourceRevision:1,status:"active" as const,taskDefinitionKey:"syntheticReviewTask",taskId:"task-1"};
const engine=():WorkflowEngine=>({cancelProcess:vi.fn(()=>Promise.resolve()),claimTask:vi.fn((_id:string,assignee:string)=>Promise.resolve({...task,assigneeReference:assignee})),completeTask:vi.fn(()=>Promise.resolve({...task,status:"completed" as const})),deployDefinition:vi.fn(()=>Promise.resolve(definition)),getDefinition:vi.fn(()=>Promise.resolve(definition)),getInstance:vi.fn(()=>Promise.resolve(instance)),getTask:vi.fn(()=>Promise.resolve(task)),health:vi.fn(()=>Promise.resolve({status:"available" as const})),listTasks:vi.fn(()=>Promise.resolve([task])),releaseTask:vi.fn(()=>Promise.resolve(task)),startProcess:vi.fn(()=>Promise.resolve(instance))});
const ports=():{audit:WorkflowAudit;authorization:WorkflowAuthorization;lifecycle:WorkflowLifecycleSink}=>({audit:{record:vi.fn(()=>Promise.resolve())},authorization:{authorize:vi.fn(()=>Promise.resolve({allowed:true,decisionId:"decision-1"}))},lifecycle:{publish:vi.fn(()=>Promise.resolve())}});
const facade=(runtime=engine(),dependencies=ports())=>createWorkflowFacade(runtime,createMemoryWorkflowCommandLedger(),dependencies.authorization,dependencies.audit,dependencies.lifecycle,{variablePolicy:{definitions:{syntheticHumanTaskV1:{routeAccepted:"boolean",sourceReference:"reference"}}}});

describe("workflow facade",()=>{
  it("starts once for concurrent identical commands and uses one stable lifecycle identity",async()=>{const runtime=engine();const dependencies=ports();const api=facade(runtime,dependencies);const command={actor,definitionKey:definition.key,definitionVersion:1,idempotencyKey:"start-1",variables:{routeAccepted:true,sourceReference:"synthetic:1"}};await expect(Promise.all([api.startProcess(command),api.startProcess(command)])).resolves.toEqual([instance,instance]);expect(runtime.startProcess).toHaveBeenCalledTimes(1);expect(dependencies.lifecycle.publish).toHaveBeenCalledTimes(2);const calls=vi.mocked(dependencies.lifecycle.publish).mock.calls;expect(calls[0]?.[0]).toEqual(calls[1]?.[0]);});
  it("rejects conflicting idempotency-key reuse",async()=>{const api=facade();await api.startProcess({actor,definitionKey:definition.key,definitionVersion:1,idempotencyKey:"start-conflict",variables:{sourceReference:"synthetic:1"}});await expect(api.startProcess({actor,definitionKey:definition.key,definitionVersion:1,idempotencyKey:"start-conflict",variables:{sourceReference:"synthetic:2"}})).rejects.toMatchObject({code:"WORKFLOW_IDEMPOTENCY_CONFLICT",retryable:false});});
  it("rejects variables outside the definition whitelist before authorization",async()=>{const runtime=engine();const dependencies=ports();await expect(facade(runtime,dependencies).startProcess({actor,definitionKey:definition.key,definitionVersion:1,idempotencyKey:"start-invalid",variables:{secret:"must-not-enter-flowable"}})).rejects.toMatchObject({code:"WORKFLOW_INVALID_INPUT"});expect(dependencies.authorization.authorize).not.toHaveBeenCalled();expect(runtime.startProcess).not.toHaveBeenCalled();});
  it("rejects inherited variable-policy keys",async()=>{const dependencies=ports();const runtime=engine();await expect(createWorkflowFacade(runtime,createMemoryWorkflowCommandLedger(),dependencies.authorization,dependencies.audit,dependencies.lifecycle,{variablePolicy:{definitions:{}}}).startProcess({actor,definitionKey:"constructor",definitionVersion:1,idempotencyKey:"prototype-policy",variables:{constructor:"unsafe"}})).rejects.toMatchObject({code:"WORKFLOW_INVALID_INPUT"});expect(dependencies.authorization.authorize).not.toHaveBeenCalled();expect(runtime.startProcess).not.toHaveBeenCalled();});
  it("propagates unknown definition versions without starting",async()=>{const runtime=engine();vi.mocked(runtime.getDefinition).mockRejectedValueOnce(new WorkflowError("WORKFLOW_UNKNOWN_DEFINITION_VERSION"));await expect(facade(runtime).startProcess({actor,definitionKey:definition.key,definitionVersion:99,idempotencyKey:"start-unknown",variables:{}})).rejects.toMatchObject({code:"WORKFLOW_UNKNOWN_DEFINITION_VERSION"});expect(runtime.startProcess).not.toHaveBeenCalled();});
  it("returns a stable duplicate completion result",async()=>{const runtime=engine();const api=facade(runtime);const command={actor,definitionKey:definition.key,idempotencyKey:"complete-1",taskId:task.taskId};const first=await api.completeTask(command);await expect(api.completeTask(command)).resolves.toEqual(first);expect(runtime.completeTask).toHaveBeenCalledTimes(1);});
  it.each([["cancelled","WORKFLOW_TASK_CANCELLED"],["completed","WORKFLOW_TASK_COMPLETED"],["expired","WORKFLOW_TASK_EXPIRED"]] as const)("fails closed for %s tasks",async(status,code)=>{const runtime=engine();vi.mocked(runtime.getTask).mockResolvedValueOnce({...task,status});await expect(facade(runtime).completeTask({actor,definitionKey:definition.key,idempotencyKey:`complete-${status}`,taskId:task.taskId})).rejects.toMatchObject({code});expect(runtime.completeTask).not.toHaveBeenCalled();});
  it("fails closed on denied authorization and unavailable attempted audit",async()=>{const denied=ports();vi.mocked(denied.authorization.authorize).mockResolvedValueOnce({allowed:false,decisionId:"decision-1"});const deniedEngine=engine();await expect(facade(deniedEngine,denied).claimTask({actor,assigneeReference:"subject-1",idempotencyKey:"claim-denied",taskId:task.taskId})).rejects.toMatchObject({code:"WORKFLOW_OPERATION_DENIED"});expect(deniedEngine.claimTask).not.toHaveBeenCalled();const unavailable=ports();vi.mocked(unavailable.audit.record).mockRejectedValueOnce(new Error("audit unavailable"));const auditEngine=engine();await expect(facade(auditEngine,unavailable).claimTask({actor,assigneeReference:"subject-1",idempotencyKey:"claim-audit",taskId:task.taskId})).rejects.toMatchObject({code:"WORKFLOW_AUDIT_FAILED"});expect(auditEngine.claimTask).not.toHaveBeenCalled();});
  it("binds claim authorization to the requested assignee",async()=>{const dependencies=ports();const runtime=engine();await facade(runtime,dependencies).claimTask({actor,assigneeReference:"subject-1",idempotencyKey:"claim-target-bound",taskId:task.taskId});expect(dependencies.authorization.authorize).toHaveBeenCalledWith(expect.objectContaining({operation:"task_claim",referenceId:task.taskId,targetAssigneeReference:"subject-1"}));});
  it("retries lifecycle publication without repeating the completed Flowable action",async()=>{const dependencies=ports();vi.mocked(dependencies.lifecycle.publish).mockRejectedValueOnce(new Error("outbox unavailable"));const runtime=engine();const api=facade(runtime,dependencies);const command={actor,definitionKey:definition.key,idempotencyKey:"complete-event-failure",taskId:task.taskId};await expect(api.completeTask(command)).rejects.toMatchObject({code:"WORKFLOW_EVENT_PUBLICATION_FAILED",retryable:true});await expect(api.completeTask(command)).resolves.toMatchObject({status:"completed"});expect(runtime.completeTask).toHaveBeenCalledTimes(1);expect(dependencies.lifecycle.publish).toHaveBeenCalledTimes(2);expect(vi.mocked(dependencies.lifecycle.publish).mock.calls[0]?.[0]).toEqual(vi.mocked(dependencies.lifecycle.publish).mock.calls[1]?.[0]);});
  it("validates completion variables before authorization and verifies the actual definition",async()=>{const dependencies=ports();const runtime=engine();const api=facade(runtime,dependencies);await expect(api.completeTask({actor,definitionKey:definition.key,idempotencyKey:"complete-invalid",taskId:task.taskId,variables:{secret:"forbidden"}})).rejects.toMatchObject({code:"WORKFLOW_INVALID_INPUT"});expect(dependencies.authorization.authorize).not.toHaveBeenCalled();vi.mocked(runtime.getInstance).mockResolvedValueOnce({...instance,definitionKey:"otherDefinition"});await expect(api.completeTask({actor,definitionKey:definition.key,idempotencyKey:"complete-mismatch",taskId:task.taskId})).rejects.toMatchObject({code:"WORKFLOW_CONFLICT"});expect(runtime.completeTask).not.toHaveBeenCalled();});
  it("scopes idempotency fingerprints to the actor",async()=>{const api=facade();const command={actor,definitionKey:definition.key,definitionVersion:1,idempotencyKey:"actor-scope",variables:{}};await api.startProcess(command);await expect(api.startProcess({...command,actor:{principalId:"principal-2"}})).rejects.toMatchObject({code:"WORKFLOW_IDEMPOTENCY_CONFLICT"});});
  it("assigns monotonic task revisions and retains them on idempotent replay",async()=>{const runtime=engine();vi.mocked(runtime.getTask).mockResolvedValueOnce(task).mockResolvedValueOnce({...task,assigneeReference:"subject-1"});const dependencies=ports();const api=facade(runtime,dependencies);const claim={actor,assigneeReference:"subject-1",idempotencyKey:"claim-revision",taskId:task.taskId};await api.claimTask(claim);await api.claimTask(claim);await api.releaseTask({actor,idempotencyKey:"release-revision",taskId:task.taskId});const events=vi.mocked(dependencies.lifecycle.publish).mock.calls.map(([event])=>event).filter((event)=>event.eventType==="workflow.task-lifecycle.v1");expect(events.map((event)=>event.data.sourceRevision)).toEqual([1,1,2]);});
  it("retains unknown remote outcomes and never repeats the mutation",async()=>{const runtime=engine();const ledger=createMemoryWorkflowCommandLedger();vi.mocked(runtime.completeTask).mockRejectedValueOnce(new WorkflowError("WORKFLOW_RECONCILIATION_REQUIRED"));const dependencies=ports();const api=createWorkflowFacade(runtime,ledger,dependencies.authorization,dependencies.audit,dependencies.lifecycle,{variablePolicy:{definitions:{syntheticHumanTaskV1:{}}}});const command={actor,definitionKey:definition.key,idempotencyKey:"complete-unknown",taskId:task.taskId};await expect(api.completeTask(command)).rejects.toMatchObject({code:"WORKFLOW_RECONCILIATION_REQUIRED",retryable:false});await expect(api.completeTask(command)).rejects.toMatchObject({code:"WORKFLOW_RECONCILIATION_REQUIRED"});expect(runtime.completeTask).toHaveBeenCalledTimes(1);await expect(ledger.getStatus({idempotencyKey:command.idempotencyKey,operation:"task_complete"})).resolves.toBe("reconciliation_required");});
  it("accepts the business-neutral BPMN subset including XML whitespace",async()=>{const runtime=engine();const xml=`<?xml version="1.0"?>
<definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL">
  <process id="${definition.key}" isExecutable="true"><startEvent id="start"/><userTask id="task"/><endEvent id="end"/></process>
</definitions>`;await expect(facade(runtime).deployDefinition({actor,assetName:"synthetic.bpmn20.xml",assetVersion:"1",bpmnXml:xml,definitionKey:definition.key,idempotencyKey:"deploy-valid"})).resolves.toEqual(definition);expect(runtime.deployDefinition).toHaveBeenCalledTimes(1);});
  it.each([
    ["extra process",`<definitions><process id="${definition.key}" isExecutable="true"><startEvent id="a"/></process><process id="other" isExecutable="true"><startEvent id="b"/></process></definitions>`],
    ["service task",`<definitions><process id="${definition.key}" isExecutable="true"><serviceTask id="unsafe" class="example.Unsafe"/></process></definitions>`],
    ["listener",`<definitions><process id="${definition.key}" isExecutable="true"><userTask id="task"><extensionElements><flowable:taskListener class="example.Unsafe"/></extensionElements></userTask></process></definitions>`],
    ["expression",'<definitions><process id="syntheticHumanTaskV1" isExecutable="true"><userTask id="task" name="${unsafe}"/></process></definitions>'],
    ["provider expression attribute",'<definitions xmlns:flowable="urn:flowable"><process id="syntheticHumanTaskV1" isExecutable="true"><userTask id="task" flowable:expression="unsafe"/></process></definitions>'],
    ["underscore-prefixed extra process",'<definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:_="http://www.omg.org/spec/BPMN/20100524/MODEL"><process id="syntheticHumanTaskV1" isExecutable="true"><userTask id="task"/></process><_:process id="extra" isExecutable="true"><_:userTask id="extraTask"/></_:process></definitions>'],
    ["underscore-prefixed service task",'<definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:_="http://www.omg.org/spec/BPMN/20100524/MODEL"><process id="syntheticHumanTaskV1" isExecutable="true"><_:serviceTask id="unsafe"/></process></definitions>'],
    ["Unicode-prefixed extra process",'<definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:流程="http://www.omg.org/spec/BPMN/20100524/MODEL"><process id="syntheticHumanTaskV1" isExecutable="true"><userTask id="task"/></process><流程:process id="extra" isExecutable="true"><流程:userTask id="extraTask"/></流程:process></definitions>'],
  ])("rejects unsafe BPMN containing %s before authorization",async(_case,xml)=>{const dependencies=ports();const runtime=engine();await expect(facade(runtime,dependencies).deployDefinition({actor,assetName:"synthetic.bpmn20.xml",assetVersion:"1",bpmnXml:xml,definitionKey:definition.key,idempotencyKey:`deploy-${String(_case).replace(" ","-")}`})).rejects.toMatchObject({code:"WORKFLOW_INVALID_INPUT"});expect(dependencies.authorization.authorize).not.toHaveBeenCalled();expect(runtime.deployDefinition).not.toHaveBeenCalled();});
  it("records denied operations without accessing Flowable",async()=>{const dependencies=ports();vi.mocked(dependencies.authorization.authorize).mockResolvedValueOnce({allowed:false,decisionId:"decision-denied"});const runtime=engine();await expect(facade(runtime,dependencies).claimTask({actor,assigneeReference:"subject-1",idempotencyKey:"claim-denied-audit",taskId:task.taskId})).rejects.toMatchObject({code:"WORKFLOW_OPERATION_DENIED"});expect(dependencies.audit.record).toHaveBeenCalledWith(expect.objectContaining({authorizationDecisionId:"decision-denied",errorCode:"WORKFLOW_OPERATION_DENIED",phase:"failed"}));expect(runtime.claimTask).not.toHaveBeenCalled();});
  it("keeps bounded observations free of variables and provider payloads",async()=>{const observations:unknown[]=[];const dependencies=ports();const api=createWorkflowFacade(engine(),createMemoryWorkflowCommandLedger(),dependencies.authorization,dependencies.audit,dependencies.lifecycle,{variablePolicy:{definitions:{syntheticHumanTaskV1:{sourceReference:"reference"}}}},{record:(event)=>{observations.push(event);}});await api.startProcess({actor,definitionKey:definition.key,definitionVersion:1,idempotencyKey:"observed-start",variables:{sourceReference:"synthetic:secret"}});expect(JSON.stringify(observations)).not.toContain("synthetic:secret");expect(observations).toContainEqual(expect.objectContaining({operation:"process_start",status:"completed"}));});
});
