import { DOMParser } from "@xmldom/xmldom";
import { performance } from "node:perf_hooks";
import { WorkflowError } from "./errors.js";
import type {
  ProcessInstance, WorkflowActor, WorkflowAudit, WorkflowAuthorization, WorkflowCommandLedger,
  WorkflowEngine, WorkflowFacade, WorkflowFacadeOptions, WorkflowLifecycleEvent,
  WorkflowLifecycleSink, WorkflowObserver, WorkflowOperation, WorkflowTask,
} from "./types.js";
import { fingerprint, validateActor, validateBounded, validateIdempotencyKey, validateKey, validateReference, validateTraceparent, validateVariables, validateVersion } from "./validation.js";

const elapsed=(start:number):number=>Math.max(0,Math.round(performance.now()-start));
const record=(observer:WorkflowObserver|undefined,event:Parameters<WorkflowObserver["record"]>[0]):void=>{try{observer?.record(event);}catch{/* Telemetry cannot affect workflow correctness. */}};
const mapped=(error:unknown,fallback="WORKFLOW_ENGINE_PROTOCOL_ERROR" as const):WorkflowError=>error instanceof WorkflowError?error:new WorkflowError(fallback,{cause:error});
const active=(task:Readonly<WorkflowTask>):void=>{if(task.status==="cancelled")throw new WorkflowError("WORKFLOW_TASK_CANCELLED");if(task.status==="completed")throw new WorkflowError("WORKFLOW_TASK_COMPLETED");if(task.status==="expired")throw new WorkflowError("WORKFLOW_TASK_EXPIRED");};
const requiredRevision=(value:number|undefined):number=>{if(value===undefined)throw new WorkflowError("WORKFLOW_ENGINE_PROTOCOL_ERROR");return value;};
const hasUnsafeXmlControl=(value:string):boolean=>{for(let index=0;index<value.length;index+=1){const code=value.charCodeAt(index);if((code<32&&code!==9&&code!==10&&code!==13)||code===127)return true;}return false;};
const BPMN_NAMESPACE="http://www.omg.org/spec/BPMN/20100524/MODEL";
const XMLNS_NAMESPACE="http://www.w3.org/2000/xmlns/";
const BPMN_ATTRIBUTES:Readonly<Record<string,ReadonlySet<string>>>=Object.freeze({definitions:new Set(["targetNamespace"]),process:new Set(["id","isExecutable","name"]),startEvent:new Set(["id","name"]),sequenceFlow:new Set(["id","name","sourceRef","targetRef"]),userTask:new Set(["id","name"]),endEvent:new Set(["id","name"])});
const bpmn=(key:string,xml:string):string=>{
  if(xml.length<1||xml.length>1_000_000||hasUnsafeXmlControl(xml))throw new WorkflowError("WORKFLOW_INVALID_INPUT");
  if(/<!DOCTYPE|<!ENTITY|\$\{|#\{/iu.test(xml))throw new WorkflowError("WORKFLOW_INVALID_INPUT");
  let document;
  try{document=new DOMParser({onError:()=>{throw new Error("Invalid BPMN XML");}}).parseFromString(xml,"application/xml");}catch(error){throw new WorkflowError("WORKFLOW_INVALID_INPUT",{cause:error});}
  const root=document.documentElement;
  if(document.doctype!==null||root===null||root.namespaceURI!==BPMN_NAMESPACE||root.localName!=="definitions")throw new WorkflowError("WORKFLOW_INVALID_INPUT");
  const elements=document.getElementsByTagName("*");
  const processes=[];
  for(let index=0;index<elements.length;index+=1){
    const element=elements.item(index);if(element===null||element.namespaceURI!==BPMN_NAMESPACE||element.localName===null)throw new WorkflowError("WORKFLOW_INVALID_INPUT");
    const allowedAttributes=BPMN_ATTRIBUTES[element.localName];if(allowedAttributes===undefined)throw new WorkflowError("WORKFLOW_INVALID_INPUT");
    if(element.localName==="definitions"&&element!==root)throw new WorkflowError("WORKFLOW_INVALID_INPUT");
    if(element.localName==="process")processes.push(element);
    for(let attributeIndex=0;attributeIndex<element.attributes.length;attributeIndex+=1){const attribute=element.attributes.item(attributeIndex);if(attribute===null)throw new WorkflowError("WORKFLOW_INVALID_INPUT");if(attribute.namespaceURI===XMLNS_NAMESPACE)continue;if(attribute.namespaceURI!==null&&attribute.namespaceURI!=="")throw new WorkflowError("WORKFLOW_INVALID_INPUT");if(attribute.localName===null||!allowedAttributes.has(attribute.localName))throw new WorkflowError("WORKFLOW_INVALID_INPUT");}
    for(let child=element.firstChild;child!==null;child=child.nextSibling){if((child.nodeType===3||child.nodeType===4)&&(child.nodeValue?.trim()??"")!=="")throw new WorkflowError("WORKFLOW_INVALID_INPUT");}
  }
  const process=processes[0];
  if(processes.length!==1||process===undefined||process.parentElement!==root||process.getAttribute("id")!==key||process.getAttribute("isExecutable")!=="true")throw new WorkflowError("WORKFLOW_INVALID_INPUT");
  return xml;
};

interface Mutation<T>{readonly actor:WorkflowActor;readonly operation:WorkflowOperation;readonly referenceId:string;readonly idempotencyKey:string;readonly payload:unknown;readonly revisionScope?:string;readonly targetAssigneeReference?:string;readonly event?: (value:T,sourceRevision:number|undefined)=>WorkflowLifecycleEvent}

export const createWorkflowFacade=(engine:WorkflowEngine,ledger:WorkflowCommandLedger,authorization:WorkflowAuthorization,audit:WorkflowAudit,lifecycle:WorkflowLifecycleSink,options:WorkflowFacadeOptions,observer?:WorkflowObserver):WorkflowFacade=>{
  const trace=():string|undefined=>validateTraceparent(options.traceparent?.());
  const observe=async<T>(operation:Parameters<WorkflowObserver["record"]>[0]["operation"],action:()=>Promise<T>):Promise<T>=>{const start=performance.now();try{const value=await action();record(observer,{durationMs:elapsed(start),operation,status:"completed"});return value;}catch(error){const failure=mapped(error);record(observer,{durationMs:elapsed(start),errorCode:failure.code,operation,status:"failed"});throw failure;}};
  const authorize=async(actorInput:WorkflowActor,operation:WorkflowOperation,referenceId:string,idempotencyKey:string,targetAssigneeReference?:string):Promise<{actor:WorkflowActor;decisionId:string}>=>{const actor=validateActor(actorInput);let decision;try{decision=await authorization.authorize({actor,operation,referenceId,...(targetAssigneeReference===undefined?{}:{targetAssigneeReference})});}catch(error){throw new WorkflowError("WORKFLOW_AUTHORIZATION_FAILED",{cause:error,retryable:true});}let decisionId;try{decisionId=validateReference(decision.decisionId);}catch(error){throw new WorkflowError("WORKFLOW_AUTHORIZATION_FAILED",{cause:error});}if(!decision.allowed){try{await audit.record({actor,authorizationDecisionId:decisionId,errorCode:"WORKFLOW_OPERATION_DENIED",idempotencyKey,operation,phase:"failed",referenceId});}catch(error){throw new WorkflowError("WORKFLOW_AUDIT_FAILED",{cause:error,retryable:true});}throw new WorkflowError("WORKFLOW_OPERATION_DENIED");}try{await audit.record({actor,authorizationDecisionId:decisionId,idempotencyKey,operation,phase:"attempted",referenceId});}catch(error){throw new WorkflowError("WORKFLOW_AUDIT_FAILED",{cause:error,retryable:true});}return{actor,decisionId};};
  const outcome=async(context:{actor:WorkflowActor;decisionId:string},operation:WorkflowOperation,referenceId:string,idempotencyKey:string,error?:WorkflowError):Promise<void>=>{try{await audit.record({actor:context.actor,authorizationDecisionId:context.decisionId,idempotencyKey,operation,phase:error===undefined?"succeeded":"failed",referenceId,...(error===undefined?{}:{errorCode:error.code})});}catch(cause){throw new WorkflowError("WORKFLOW_AUDIT_FAILED",{cause,retryable:true});}};
  const mutate=async<T>(input:Mutation<T>,action:()=>Promise<T>):Promise<T>=>observe(input.operation,async()=>{const idempotencyKey=validateIdempotencyKey(input.idempotencyKey);const context=await authorize(input.actor,input.operation,input.referenceId,idempotencyKey,input.targetAssigneeReference);let result;try{result=await ledger.execute({fingerprint:fingerprint({actorPrincipalId:context.actor.principalId,payload:input.payload}),idempotencyKey,operation:input.operation,...(input.revisionScope===undefined?{}:{revisionScope:input.revisionScope})},action);}catch(error){const failure=mapped(error);await outcome(context,input.operation,input.referenceId,idempotencyKey,failure);throw failure;}if(input.event!==undefined){try{await lifecycle.publish(input.event(result.value,result.sourceRevision));}catch(error){const failure=new WorkflowError("WORKFLOW_EVENT_PUBLICATION_FAILED",{cause:error,retryable:true});await outcome(context,input.operation,input.referenceId,idempotencyKey,failure);throw failure;}}await outcome(context,input.operation,input.referenceId,idempotencyKey);return result.value;});
  const facade:WorkflowFacade={
    async cancelProcess(command){const id=validateReference(command.processInstanceId);const reason=validateBounded(command.reason,256);return mutate<ProcessInstance>({actor:command.actor,idempotencyKey:command.idempotencyKey,operation:"process_cancel",payload:{id,reason},referenceId:id,event:(value)=>({eventType:"workflow.process-lifecycle.v1",data:{...value,eventKey:fingerprint({idempotencyKey:command.idempotencyKey,operation:"process_cancel"}),occurrence:"cancelled"}})},async()=>{const current=await engine.getInstance(id,trace());if(current.status!=="active")throw new WorkflowError("WORKFLOW_CONFLICT");await engine.cancelProcess(id,reason,trace());try{return await engine.getInstance(id,trace());}catch(error){throw new WorkflowError("WORKFLOW_RECONCILIATION_REQUIRED",{cause:error});}});},
    async claimTask(command){const id=validateReference(command.taskId);const assignee=validateReference(command.assigneeReference);return mutate<WorkflowTask>({actor:command.actor,idempotencyKey:command.idempotencyKey,operation:"task_claim",payload:{assignee,id},referenceId:id,revisionScope:id,targetAssigneeReference:assignee,event:(value,revision)=>({eventType:"workflow.task-lifecycle.v1",data:{...value,eventKey:fingerprint({idempotencyKey:command.idempotencyKey,operation:"task_claim"}),occurrence:"claimed",sourceRevision:requiredRevision(revision)}})},async()=>{active(await engine.getTask(id,trace()));return engine.claimTask(id,assignee,trace());});},
    async completeTask(command){const id=validateReference(command.taskId);const key=validateKey(command.definitionKey);const variables=validateVariables(options.variablePolicy,key,command.variables??{});return mutate<WorkflowTask>({actor:command.actor,idempotencyKey:command.idempotencyKey,operation:"task_complete",payload:{id,key,variables},referenceId:id,revisionScope:id,event:(value,revision)=>({eventType:"workflow.task-lifecycle.v1",data:{...value,eventKey:fingerprint({idempotencyKey:command.idempotencyKey,operation:"task_complete"}),occurrence:"completed",sourceRevision:requiredRevision(revision)}})},async()=>{const task=await engine.getTask(id,trace());active(task);const instance=await engine.getInstance(task.processInstanceId,trace());if(instance.definitionKey!==key)throw new WorkflowError("WORKFLOW_CONFLICT");return engine.completeTask(id,variables,trace());});},
    async deployDefinition(command){const key=validateKey(command.definitionKey);const assetName=validateBounded(command.assetName,255);const assetVersion=validateBounded(command.assetVersion,64);const xml=bpmn(key,command.bpmnXml);return mutate({actor:command.actor,idempotencyKey:command.idempotencyKey,operation:"definition_deploy",payload:{assetName,assetVersion,bpmnSha256:fingerprint(xml),key},referenceId:key},()=>{const currentTrace=trace();return engine.deployDefinition({assetName,bpmnXml:xml,definitionKey:key,...(currentTrace===undefined?{}:{traceparent:currentTrace})});});},
    getDefinition:(key,version)=>observe("definition_query",()=>engine.getDefinition(validateKey(key),validateVersion(version),trace())),
    getInstance:(id)=>observe("instance_query",()=>engine.getInstance(validateReference(id),trace())),
    health:()=>observe("health",()=>engine.health()),
    listTasks:(id)=>observe("task_query",()=>engine.listTasks(validateReference(id),trace())),
    async releaseTask(command){const id=validateReference(command.taskId);return mutate<WorkflowTask>({actor:command.actor,idempotencyKey:command.idempotencyKey,operation:"task_release",payload:{id},referenceId:id,revisionScope:id,event:(value,revision)=>({eventType:"workflow.task-lifecycle.v1",data:{...value,eventKey:fingerprint({idempotencyKey:command.idempotencyKey,operation:"task_release"}),occurrence:"released",sourceRevision:requiredRevision(revision)}})},async()=>{const task=await engine.getTask(id,trace());active(task);if(task.assigneeReference===undefined)throw new WorkflowError("WORKFLOW_CONFLICT");return engine.releaseTask(id,trace());});},
    async startProcess(command){const key=validateKey(command.definitionKey);const version=validateVersion(command.definitionVersion);const variables=validateVariables(options.variablePolicy,key,command.variables);return mutate<ProcessInstance>({actor:command.actor,idempotencyKey:command.idempotencyKey,operation:"process_start",payload:{key,variables,version},referenceId:key,event:(value)=>({eventType:"workflow.process-lifecycle.v1",data:{...value,eventKey:fingerprint({idempotencyKey:command.idempotencyKey,operation:"process_start"}),occurrence:"started"}})},async()=>{const definition=await engine.getDefinition(key,version,trace());const currentTrace=trace();return engine.startProcess({businessKey:command.idempotencyKey,definition,variables,...(currentTrace===undefined?{}:{traceparent:currentTrace})});});},
  };return Object.freeze(facade);
};
