import { sql } from "drizzle-orm";
import { boolean, check, foreignKey, index, integer, pgSchema, text, timestamp, unique, uuid, varchar } from "drizzle-orm/pg-core";
const registry = pgSchema("app_registry");
export const applications = registry.table("applications", { applicationId: varchar("application_id", { length: 128 }).primaryKey(), audience: varchar("audience", { length: 16 }).notNull(), enabled: boolean("enabled").notNull(), permissionCode: varchar("permission_code", { length: 129 }).notNull() }, (table) => [check("applications_audience_check", sql`${table.audience} in ('internal','external')`)]);
export const routes = registry.table("routes", { routeId: varchar("route_id", { length: 128 }).primaryKey(), applicationId: varchar("application_id", { length: 128 }).notNull().references(() => applications.applicationId), path: varchar("path", { length: 256 }).notNull(), enabled: boolean("enabled").notNull(), permissionCode: varchar("permission_code", { length: 129 }).notNull(), deepLinkSources: text("deep_link_sources").array().notNull() }, (table) => [unique("routes_application_route_unique").on(table.applicationId, table.routeId), check("routes_path_safe", sql`${table.path} ~ '^/[a-z0-9_./:-]{0,255}$' and ${table.path} !~ '//|\\.\\.|[?#]'`), check("routes_sources_safe", sql`${table.deepLinkSources} <@ array['task','notification']::text[]`), index("routes_application_idx").on(table.applicationId)]);
export const navigation = registry.table("navigation", { navigationId: varchar("navigation_id", { length: 128 }).primaryKey(), applicationId: varchar("application_id", { length: 128 }).notNull().references(() => applications.applicationId), routeId: varchar("route_id", { length: 128 }).notNull(), parentNavigationId: varchar("parent_navigation_id", { length: 128 }), enabled: boolean("enabled").notNull(), displayOrder: integer("display_order").notNull() }, (table) => [
  check("navigation_order_check", sql`${table.displayOrder} between 0 and 100000`),
  check("navigation_not_self_parent_check", sql`${table.parentNavigationId} is null or ${table.parentNavigationId} <> ${table.navigationId}`),
  unique("navigation_application_id_unique").on(table.applicationId, table.navigationId),
  foreignKey({ columns: [table.applicationId, table.routeId], foreignColumns: [routes.applicationId, routes.routeId], name: "navigation_route_fk" }),
  foreignKey({ columns: [table.applicationId, table.parentNavigationId], foreignColumns: [table.applicationId, table.navigationId], name: "navigation_parent_fk" }),
  index("navigation_application_order_idx").on(table.applicationId, table.displayOrder),
]);
export const operationReceipts = registry.table("operation_receipts", { operationId: uuid("operation_id").primaryKey(), fingerprint: varchar("fingerprint", { length: 64 }).notNull(), recordedAt: timestamp("recorded_at", { mode: "string", withTimezone: true }).defaultNow().notNull() }, (table) => [check("app_registry_receipts_fingerprint_length", sql`length(${table.fingerprint}) = 64`)]);
