import { createHash } from "node:crypto";
import { readdir, readFile, writeFile } from "node:fs/promises";
import { relative, resolve } from "node:path";
import { fileURLToPath, URL } from "node:url";
import SwaggerParser from "@apidevtools/swagger-parser";
import { Parser as AsyncApiParser } from "@asyncapi/parser";
import Ajv2020 from "ajv/dist/2020.js";
import YAML from "yaml";

const methods = ["get", "put", "post", "delete", "options", "head", "patch", "trace"];
const compareStable = (left, right) => left.localeCompare(right, "en");

async function walk(directory, predicate) {
  const entries = await readdir(directory, { withFileTypes: true });
  const results = [];
  for (const entry of entries) {
    const path = resolve(directory, entry.name);
    if (entry.isDirectory()) results.push(...(await walk(path, predicate)));
    else if (predicate(path)) results.push(path);
  }
  return results.sort(compareStable);
}

function stable(value) {
  if (Array.isArray(value)) return value.map(stable);
  if (value && typeof value === "object") {
    return Object.fromEntries(Object.entries(value).sort(([left], [right]) => compareStable(left, right)).map(([key, item]) => [key, stable(item)]));
  }
  return value;
}

function json(value) {
  return `${JSON.stringify(stable(value), null, 2)}\n`;
}

function selectPaths(paths, audience) {
  const selected = {};
  for (const [path, pathItem] of Object.entries(paths)) {
    const next = {};
    for (const [key, operation] of Object.entries(pathItem)) {
      if (!methods.includes(key)) {
        next[key] = operation;
        continue;
      }
      const audiences = operation["x-ai-crm-audiences"];
      if (!Array.isArray(audiences) || !audiences.every((item) => ["internal", "external"].includes(item))) {
        throw new Error(`${operation.operationId ?? `${key} ${path}`} must declare reviewed x-ai-crm-audiences.`);
      }
      if (audiences.includes(audience)) next[key] = operation;
    }
    if (methods.some((method) => method in next)) selected[path] = next;
  }
  return selected;
}

function decodePointerSegment(segment) {
  return segment.replaceAll("~1", "/").replaceAll("~0", "~");
}

export function selectReferencedSchemas(schemas, paths) {
  const pending = [];
  const selected = {};

  const collectReferences = (value) => {
    if (Array.isArray(value)) {
      for (const item of value) collectReferences(item);
      return;
    }
    if (!value || typeof value !== "object") return;
    const reference = value.$ref;
    if (typeof reference === "string" && reference.startsWith("#/components/schemas/")) {
      pending.push(decodePointerSegment(reference.slice("#/components/schemas/".length)));
    }
    for (const item of Object.values(value)) collectReferences(item);
  };

  collectReferences(paths);
  while (pending.length > 0) {
    const name = pending.shift();
    if (!name || name in selected) continue;
    const schema = schemas[name];
    if (schema === undefined) throw new Error(`OpenAPI references missing schema ${name}.`);
    selected[name] = schema;
    collectReferences(schema);
  }
  return selected;
}

function renderClient(document, audience) {
  const operations = [];
  for (const [path, pathItem] of Object.entries(document.paths)) {
    for (const method of methods) {
      const operation = pathItem[method];
      if (operation) operations.push({ id: operation.operationId, method: method.toUpperCase(), path });
    }
  }
  const exportName = audience === "external" ? "externalOperations" : "internalOperations";
  return [
    "// @generated by scripts/contracts/generate.mjs. Do not edit.",
    audience === "internal" ? 'export const packageId = "@ai-crm/api-client" as const;' : undefined,
    `export const ${exportName} = ${JSON.stringify(operations, null, 2)} as const;`,
    "",
  ].filter((line) => line !== undefined).join("\n");
}

export async function renderArtifacts(root) {
  const moduleDirectory = resolve(root, "contracts/http/modules");
  const modules = await walk(moduleDirectory, (path) => path.endsWith(".yaml"));
  const bundle = {
    openapi: "3.1.0",
    info: { title: "AI-CRM API", version: "0.1.0" },
    paths: {},
    components: { schemas: {} },
    "x-ai-crm-generated": true,
  };

  for (const path of modules) {
    const document = YAML.parse(await readFile(path, "utf8"));
    await SwaggerParser.validate(document);
    for (const [route, pathItem] of Object.entries(document.paths ?? {})) {
      if (route in bundle.paths) throw new Error(`Duplicate OpenAPI path ${route}.`);
      bundle.paths[route] = pathItem;
    }
    Object.assign(bundle.components.schemas, document.components?.schemas ?? {});
  }

  const internalPaths = selectPaths(bundle.paths, "internal");
  const externalPaths = selectPaths(bundle.paths, "external");
  const internal = {
    ...bundle,
    components: { schemas: selectReferencedSchemas(bundle.components.schemas, internalPaths) },
    paths: internalPaths,
  };
  const external = {
    ...bundle,
    components: { schemas: selectReferencedSchemas(bundle.components.schemas, externalPaths) },
    info: { ...bundle.info, title: "AI-CRM External API" },
    paths: externalPaths,
  };
  await SwaggerParser.validate(internal);
  await SwaggerParser.validate(external);

  const schemaPaths = await walk(resolve(root, "contracts"), (path) => path.endsWith(".schema.json"));
  const ajv = new Ajv2020({ allErrors: true, strict: true });
  for (const path of schemaPaths) {
    const schema = JSON.parse(await readFile(path, "utf8"));
    if (!schema.$id?.match(/\/v\d+\//)) throw new Error(`${relative(root, path)} must use a versioned $id.`);
    ajv.compile(schema);
  }

  const asyncApiPaths = await walk(resolve(root, "contracts/asyncapi"), (path) => path.endsWith(".yaml"));
  const asyncApiParser = new AsyncApiParser();
  for (const path of asyncApiPaths) {
    const source = await readFile(path, "utf8");
    const result = await asyncApiParser.parse(source, { source: path });
    if (result.diagnostics.some((item) => item.severity === 0)) {
      throw new Error(`${relative(root, path)} is not valid AsyncAPI: ${result.diagnostics.map((item) => item.message).join("; ")}`);
    }
  }

  const artifacts = new Map([
    ["contracts/generated/internal.openapi.json", json(internal)],
    ["contracts/generated/external.openapi.json", json(external)],
    ["packages/api-client/src/index.ts", renderClient(internal, "internal")],
    ["packages/api-client/src/external.ts", renderClient(external, "external")],
  ]);
  const hashes = Object.fromEntries([...artifacts].map(([path, content]) => [path, createHash("sha256").update(content).digest("hex")]));
  artifacts.set("contracts/generated/manifest.json", json({ generatedBy: "scripts/contracts/generate.mjs", sha256: hashes }));
  return artifacts;
}

export async function checkArtifacts(root, artifacts) {
  const errors = [];
  for (const [path, expected] of artifacts) {
    try {
      const actual = await readFile(resolve(root, path), "utf8");
      if (actual !== expected) errors.push(`${path} differs from its generated source.`);
    } catch {
      errors.push(`${path} is missing.`);
    }
  }
  return errors;
}

async function main() {
  const root = resolve(fileURLToPath(new URL("../..", import.meta.url)));
  const artifacts = await renderArtifacts(root);
  if (process.argv.includes("--check")) {
    const errors = await checkArtifacts(root, artifacts);
    if (errors.length > 0) {
      for (const error of errors) console.error(error);
      process.exit(1);
    }
    console.log("Contract sources and generated artifacts are valid.");
    return;
  }
  for (const [path, content] of artifacts) await writeFile(resolve(root, path), content);
  console.log(`Generated ${artifacts.size} contract artifacts.`);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) await main();
