import { readFile } from "node:fs/promises";
import { Ajv2020 } from "ajv/dist/2020.js";
import { describe,expect,it } from "vitest";
import { validateEvent } from "./validation.js";
import type { TaskLifecycleEvent } from "./types.js";

describe("Task Center event contract",()=>{
  it("maps non-object lifecycle input to the stable validation error",()=>{expect(()=>validateEvent(null as unknown as TaskLifecycleEvent)).toThrow("TASK_INPUT_INVALID");});
  it("accepts a business-neutral stable-route lifecycle event and rejects URLs",async()=>{const schema=JSON.parse(await readFile(new URL("../../../../contracts/events/task-projection-lifecycle.v1.schema.json",import.meta.url),"utf8")) as object;const validate=new Ajv2020({strict:true,validateFormats:false}).compile(schema);const value={eventId:"43000000-0000-4000-8000-000000000001",sourceType:"workflow",sourceTaskId:"task.synthetic",sourceVersion:1,occurredAt:"2026-07-26T00:00:00.000Z",status:"open",deepLink:{appId:"workbench",routeId:"task-detail"}};expect(validate(value),JSON.stringify(validate.errors)).toBe(true);expect(validate({...value,deepLink:{appId:"https://outside.invalid",routeId:"task-detail"}})).toBe(false);});
  it("keeps schema and runtime UTC timestamp boundaries aligned",async()=>{const schema=JSON.parse(await readFile(new URL("../../../../contracts/events/task-projection-lifecycle.v1.schema.json",import.meta.url),"utf8")) as object;const validate=new Ajv2020({strict:true,validateFormats:false}).compile(schema);const base={eventId:"43000000-0000-4000-8000-000000000001",sourceType:"workflow",sourceTaskId:"task.synthetic",sourceVersion:1,status:"open",deepLink:{appId:"workbench",routeId:"task-detail"}};for(const timestamp of ["2026-07-26T00:00:00Z","2026-07-26T00:00:00.1Z","2026-07-26T00:00:00.123456789Z"]){const value={...base,occurredAt:timestamp,dueAt:timestamp} as TaskLifecycleEvent;expect(validate(value),JSON.stringify(validate.errors)).toBe(true);expect(()=>validateEvent(value)).not.toThrow();}for(const timestamp of ["2026-07-26T08:00:00+08:00","2026-07-26T00:00:00.1234567890Z"]){const value={...base,occurredAt:timestamp,dueAt:timestamp} as TaskLifecycleEvent;expect(validate(value)).toBe(false);expect(()=>validateEvent(value)).toThrow();}});
  it.each(["2026-02-29T00:00:00Z","2026-04-31T00:00:00Z","2026-07-26T24:00:00Z"])("rejects lexically shaped but invalid RFC3339 calendar value %s at runtime",async(timestamp)=>{const schema=JSON.parse(await readFile(new URL("../../../../contracts/events/task-projection-lifecycle.v1.schema.json",import.meta.url),"utf8")) as object;const validate=new Ajv2020({strict:true,validateFormats:false}).compile(schema);const base={eventId:"43000000-0000-4000-8000-000000000001",sourceType:"workflow",sourceTaskId:"task.synthetic",sourceVersion:1,status:"open",deepLink:{appId:"workbench",routeId:"task-detail"}};expect(validate({...base,occurredAt:timestamp,dueAt:timestamp})).toBe(true);expect(()=>validateEvent({...base,occurredAt:timestamp,dueAt:"2026-07-26T00:00:00Z"} as TaskLifecycleEvent)).toThrow();expect(()=>validateEvent({...base,occurredAt:"2026-07-26T00:00:00Z",dueAt:timestamp} as TaskLifecycleEvent)).toThrow();});
});
