import { randomUUID } from "node:crypto";
import { describe,expect,it,vi } from "vitest";
import { TaskCenterError } from "./errors.js";
import { InMemoryTaskCenterStore } from "./memory-store.js";
import { createTaskCenter } from "./service.js";
import type { TaskAudit,TaskAuthorization,TaskCenterStore,TaskLifecycleEvent,TaskSourceCommandRouter,TaskSourceReader } from "./types.js";
import { fingerprint } from "./validation.js";

const actor={principalId:"principal.synthetic"};
const event=(overrides:Partial<TaskLifecycleEvent>={}):TaskLifecycleEvent=>({eventId:randomUUID(),sourceType:"workflow",sourceTaskId:"task.synthetic",sourceVersion:1,occurredAt:"2026-07-26T00:00:00.000Z",status:"open",deepLink:{appId:"workbench",routeId:"task-detail"},...overrides});
const setup=(options:{allowed?:(operation:string,taskId?:string)=>boolean;router?:TaskSourceCommandRouter;reader?:TaskSourceReader;store?:TaskCenterStore;now?:()=>number;commandLeaseMs?:number;commandLeaseToken?:()=>string}={})=>{const audits:unknown[]=[];const authorization:TaskAuthorization={authorize:vi.fn((input: Parameters<TaskAuthorization["authorize"]>[0])=>Promise.resolve({allowed:options.allowed?.(input.operation,input.task?.sourceTaskId)??true,decisionId:"decision.synthetic"}))};const audit:TaskAudit={record:vi.fn((input)=>{audits.push(input);return Promise.resolve();})};const complete=vi.fn(()=>Promise.resolve({sourceCommandId:"command.synthetic",status:"accepted" as const}));const router:TaskSourceCommandRouter=options.router??{complete};const reader=options.reader??{get:vi.fn(()=>Promise.resolve(event({sourceVersion:2,status:"completed"})))};const store=options.store??new InMemoryTaskCenterStore();return{audits,authorization,complete,reader,store,service:createTaskCenter({store,authorization,audit,router,sourceReader:reader,...(options.now?{now:options.now}:{}),...(options.commandLeaseMs?{commandLeaseMs:options.commandLeaseMs}:{}),...(options.commandLeaseToken?{commandLeaseToken:options.commandLeaseToken}:{})})};};

describe("Task Center",()=>{
  it("passes the caller abort signal to projection persistence",async()=>{const base=new InMemoryTaskCenterStore();const apply=vi.fn((input:TaskLifecycleEvent,signal?:AbortSignal)=>base.apply(input,signal));const store:TaskCenterStore={apply,reconcile:(input)=>base.reconcile(input),get:(input)=>base.get(input),list:(input)=>base.list(input),claimCommand:(input)=>base.claimCommand(input),releaseCommand:(input)=>base.releaseCommand(input),acceptCommand:(input)=>base.acceptCommand(input)};const controller=new AbortController();await setup({store}).service.apply(event(),controller.signal);expect(apply).toHaveBeenCalledWith(expect.any(Object),controller.signal);});
  it("applies lifecycle events idempotently and ignores older source revisions",async()=>{const {service}=setup();const created=event();expect((await service.apply(created)).status).toBe("applied");expect((await service.apply(created)).status).toBe("duplicate");expect((await service.apply(event({eventId:randomUUID(),sourceVersion:3,status:"completed"}))).projection.status).toBe("completed");const stale=await service.apply(event({eventId:randomUUID(),sourceVersion:2,status:"open"}));expect(stale.status).toBe("stale");expect(stale.projection).toMatchObject({sourceVersion:3,status:"completed"});});
  it("deduplicates recursively reordered event properties but rejects substantive changes",async()=>{const {service}=setup();const first=event({deepLink:{appId:"workbench",routeId:"task-detail"}});await service.apply(first);const reordered={deepLink:{routeId:first.deepLink.routeId,appId:first.deepLink.appId},status:first.status,occurredAt:first.occurredAt,sourceVersion:first.sourceVersion,sourceTaskId:first.sourceTaskId,sourceType:first.sourceType,eventId:first.eventId};await expect(service.apply(reordered)).resolves.toMatchObject({status:"duplicate"});await expect(service.apply({...reordered,status:"cancelled"})).rejects.toMatchObject({code:"TASK_COMMAND_CONFLICT"});});
  it.each(["2026-07-26T00:00:00Z","2026-07-26T00:00:00.1Z","2026-07-26T00:00:00.123456789Z","2024-02-29T23:59:59Z"])("accepts reviewed UTC timestamp boundary %s",async(timestamp)=>{const {service}=setup();await expect(service.apply(event({occurredAt:timestamp,dueAt:timestamp}))).resolves.toMatchObject({status:"applied"});});
  it.each(["2026-07-26T08:00:00+08:00","2026-07-26T00:00Z","2026-07-26T00:00:00.1234567890Z","2026-13-26T00:00:00Z","2026-02-29T00:00:00Z","2026-04-31T00:00:00Z","2026-07-26T24:00:00Z"])("rejects non-contract timestamp %s for occurredAt and dueAt",async(timestamp)=>{await expect(setup().service.apply(event({occurredAt:timestamp}))).rejects.toMatchObject({code:"TASK_INPUT_INVALID"});await expect(setup().service.apply(event({dueAt:timestamp}))).rejects.toMatchObject({code:"TASK_INPUT_INVALID"});});
  it("routes completion to the source idempotently without closing the projection",async()=>{const {service,complete}=setup();await service.apply(event());const command={actor,idempotencyKey:"idem.synthetic",sourceType:"workflow",sourceTaskId:"task.synthetic"};await expect(service.complete(command)).resolves.toEqual({sourceCommandId:"command.synthetic",status:"accepted"});await expect(service.complete(command)).resolves.toEqual({sourceCommandId:"command.synthetic",status:"accepted"});expect(complete).toHaveBeenCalledTimes(1);await expect(service.get(actor,command)).resolves.toMatchObject({status:"open"});});
  it("fails closed on current object authorization and filters list results",async()=>{const {service}=setup({allowed:(operation,taskId)=>operation!=="task_detail"||taskId!=="task.hidden"});await service.apply(event());await service.apply(event({eventId:randomUUID(),sourceTaskId:"task.hidden"}));await expect(service.get(actor,{sourceType:"workflow",sourceTaskId:"task.hidden"})).rejects.toMatchObject({code:"TASK_OPERATION_DENIED"});await expect(service.list({actor})).resolves.toMatchObject({items:[expect.objectContaining({sourceTaskId:"task.synthetic"})]});});
  it("releases a failed source command for recovery with the same idempotency key",async()=>{const complete=vi.fn().mockRejectedValueOnce(new Error("source unavailable")).mockResolvedValueOnce({sourceCommandId:"command.retry",status:"accepted"});const {service}=setup({router:{complete}});await service.apply(event());const command={actor,idempotencyKey:"idem.retry",sourceType:"workflow",sourceTaskId:"task.synthetic"};await expect(service.complete(command)).rejects.toMatchObject({code:"TASK_SOURCE_UNAVAILABLE",retryable:true});await expect(service.complete(command)).resolves.toMatchObject({sourceCommandId:"command.retry"});expect(complete).toHaveBeenCalledTimes(2);});
  it.each([null,[],{sourceCommandId:"bad id",status:"accepted"},{sourceCommandId:"command.synthetic",status:"wrong"},{sourceCommandId:"command.synthetic",status:"accepted",extra:true}])("rejects malformed source result %# and permits retry",async(result)=>{const complete=vi.fn().mockResolvedValueOnce(result).mockResolvedValueOnce({sourceCommandId:"command.retry",status:"accepted"});const {service}=setup({router:{complete} as TaskSourceCommandRouter});await service.apply(event());const command={actor,idempotencyKey:`idem.${randomUUID()}`,sourceType:"workflow",sourceTaskId:"task.synthetic"};await expect(service.complete(command)).rejects.toMatchObject({code:"TASK_SOURCE_UNAVAILABLE",retryable:true});await expect(service.complete(command)).resolves.toEqual({sourceCommandId:"command.retry",status:"accepted"});expect(complete).toHaveBeenCalledTimes(2);});
  it("reports an active command lease as retryable without calling the source",async()=>{const store=new InMemoryTaskCenterStore();const now=Date.parse("2026-07-26T00:00:00Z");const command={actor,idempotencyKey:"idem.running",sourceType:"workflow",sourceTaskId:"task.synthetic"};await store.claimCommand({idempotencyKey:command.idempotencyKey,fingerprint:fingerprint({actor:actor.principalId,sourceType:command.sourceType,sourceTaskId:command.sourceTaskId}),leaseToken:"43000000-0000-4000-8000-000000000001",now:new Date(now),leaseExpiresAt:new Date(now+30_000)});const {service,complete}=setup({store,now:()=>now,commandLeaseToken:()=>"43000000-0000-4000-8000-000000000002"});await service.apply(event());await expect(service.complete(command)).rejects.toMatchObject({code:"TASK_COMMAND_IN_PROGRESS",retryable:true});expect(complete).not.toHaveBeenCalled();});
  it("takes over an expired lease left before source dispatch",async()=>{const store=new InMemoryTaskCenterStore();let clock=Date.parse("2026-07-26T00:00:00Z");const command={actor,idempotencyKey:"idem.takeover",sourceType:"workflow",sourceTaskId:"task.synthetic"};await store.claimCommand({idempotencyKey:command.idempotencyKey,fingerprint:fingerprint({actor:actor.principalId,sourceType:command.sourceType,sourceTaskId:command.sourceTaskId}),leaseToken:"43000000-0000-4000-8000-000000000001",now:new Date(clock),leaseExpiresAt:new Date(clock+1_000)});clock+=1_001;const {service,complete}=setup({store,now:()=>clock,commandLeaseMs:1_000,commandLeaseToken:()=>"43000000-0000-4000-8000-000000000002"});await service.apply(event());await expect(service.complete(command)).resolves.toEqual({sourceCommandId:"command.synthetic",status:"accepted"});expect(complete).toHaveBeenCalledTimes(1);});
  it("recovers after source acceptance and lost receipt ownership using source idempotency",async()=>{const base=new InMemoryTaskCenterStore();let rejectFirstAccept=true;const store:TaskCenterStore={apply:(input)=>base.apply(input),reconcile:(input)=>base.reconcile(input),get:(input)=>base.get(input),list:(input)=>base.list(input),claimCommand:(input)=>base.claimCommand(input),releaseCommand:(input)=>base.releaseCommand(input),acceptCommand:async(input)=>rejectFirstAccept?(rejectFirstAccept=false,false):base.acceptCommand(input)};let clock=Date.parse("2026-07-26T00:00:00Z");let token=1;const effects=new Map<string,{sourceCommandId:string;status:"accepted"}>();const complete=vi.fn((input:{idempotencyKey:string})=>{const result=effects.get(input.idempotencyKey)??{sourceCommandId:"command.once",status:"accepted" as const};effects.set(input.idempotencyKey,result);return Promise.resolve(result);});const {service}=setup({store,router:{complete} as TaskSourceCommandRouter,now:()=>clock,commandLeaseMs:1_000,commandLeaseToken:()=>`43000000-0000-4000-8000-${String(token++).padStart(12,"0")}`});await service.apply(event());const command={actor,idempotencyKey:"idem.ambiguous",sourceType:"workflow",sourceTaskId:"task.synthetic"};await expect(service.complete(command)).rejects.toMatchObject({code:"TASK_COMMAND_IN_PROGRESS",retryable:true});clock+=1_001;await expect(service.complete(command)).resolves.toEqual({sourceCommandId:"command.once",status:"accepted"});await expect(service.complete(command)).resolves.toEqual({sourceCommandId:"command.once",status:"accepted"});expect(complete).toHaveBeenCalledTimes(2);expect(effects).toHaveLength(1);});
  it("rejects reuse of a command idempotency key by another principal",async()=>{const {service}=setup();await service.apply(event());const command={actor,idempotencyKey:"idem.conflict",sourceType:"workflow",sourceTaskId:"task.synthetic"};await service.complete(command);await expect(service.complete({...command,actor:{principalId:"principal.other"}})).rejects.toMatchObject({code:"TASK_COMMAND_CONFLICT"});});
  it("repairs a drifted projection from the authoritative source",async()=>{const authoritative=event({eventId:randomUUID(),sourceVersion:4,status:"cancelled"});const {service}=setup({reader:{get:vi.fn(()=>Promise.resolve(authoritative))}});await service.apply(event());await expect(service.reconcile(actor,{sourceType:"workflow",sourceTaskId:"task.synthetic"})).resolves.toMatchObject({status:"applied",projection:{sourceVersion:4,status:"cancelled"}});});
  it("reports an older authoritative reconciliation snapshot as stale",async()=>{const {service}=setup({reader:{get:vi.fn(()=>Promise.resolve(event({eventId:randomUUID(),sourceVersion:2})))}});await service.apply(event({sourceVersion:3,status:"completed"}));await expect(service.reconcile(actor,{sourceType:"workflow",sourceTaskId:"task.synthetic"})).resolves.toMatchObject({status:"stale",projection:{sourceVersion:3,status:"completed"}});});
  it("repairs same-version projection drift from the authoritative snapshot",async()=>{const authoritative=event({eventId:randomUUID(),sourceVersion:3,status:"completed"});const {service}=setup({reader:{get:vi.fn(()=>Promise.resolve(authoritative))}});await service.apply(event({sourceVersion:3,status:"open"}));await expect(service.reconcile(actor,{sourceType:"workflow",sourceTaskId:"task.synthetic"})).resolves.toMatchObject({status:"applied",projection:{sourceVersion:3,status:"completed"}});});
  it("rejects arbitrary URLs and malformed stable route identifiers",async()=>{const {service}=setup();await expect(service.apply({...event(),deepLink:{appId:"https://outside.invalid",routeId:"task detail"}})).rejects.toBeInstanceOf(TaskCenterError);});
});
