import { randomUUID } from "node:crypto";
import { TaskCenterError } from "./errors.js";
import { fingerprint, validateActor, validateEvent, validateId, validateKey, validateSourceCommandResult, validateUuid } from "./validation.js";
import type { CompleteTaskCommand, ReconciliationResult, TaskActor, TaskAudit, TaskAuthorization, TaskCenter, TaskCenterStore, TaskObserver, TaskOperation, TaskProjection, TaskProjectionKey, TaskQuery, TaskSourceCommandRouter, TaskSourceReader } from "./types.js";

const mapped = (error: unknown, fallback: "TASK_SOURCE_UNAVAILABLE" | "TASK_STORAGE_UNAVAILABLE"): TaskCenterError => error instanceof TaskCenterError ? error : new TaskCenterError(fallback,{cause:error,retryable:true});
export const createTaskCenter = (ports: { readonly store: TaskCenterStore; readonly authorization: TaskAuthorization; readonly audit: TaskAudit; readonly router: TaskSourceCommandRouter; readonly sourceReader: TaskSourceReader; readonly observer?: TaskObserver; readonly now?: () => number; readonly commandLeaseMs?: number; readonly commandLeaseToken?: () => string }): TaskCenter => {
  const now=ports.now??Date.now;
  const commandLeaseMs=ports.commandLeaseMs??30_000;if(!Number.isSafeInteger(commandLeaseMs)||commandLeaseMs<1_000||commandLeaseMs>300_000)throw new TaskCenterError("TASK_INPUT_INVALID");
  const commandLeaseToken=ports.commandLeaseToken??randomUUID;
  const observe=async<T>(operation:TaskOperation|"projection_apply",work:()=>Promise<T>):Promise<T>=>{const started=now();try{const result=await work();ports.observer?.record({operation,outcome:"completed",durationMs:Math.max(0,now()-started)});return result;}catch(error){ports.observer?.record({operation,outcome:error instanceof TaskCenterError&&error.code==="TASK_OPERATION_DENIED"?"denied":"failed",durationMs:Math.max(0,now()-started)});throw error;}};
  const recordAudit=async(input:Parameters<TaskAudit["record"]>[0]):Promise<void>=>{try{await ports.audit.record(input);}catch(error){throw new TaskCenterError("TASK_AUDIT_FAILED",{cause:error,retryable:true});}};
  const authorize=async(actorInput:TaskActor,operation:TaskOperation,key?:TaskProjectionKey):Promise<{actor:TaskActor;decisionId:string}>=>{const actor=validateActor(actorInput);let decision;try{decision=await ports.authorization.authorize({actor,operation,...(key===undefined?{}:{task:key})});}catch(error){throw new TaskCenterError("TASK_AUTHORIZATION_FAILED",{cause:error,retryable:true});}let decisionId;try{decisionId=validateId(decision.decisionId);}catch(error){throw new TaskCenterError("TASK_AUTHORIZATION_FAILED",{cause:error});}const referenceId=key===undefined?actor.principalId:`${key.sourceType}:${key.sourceTaskId}`;if(!decision.allowed){await recordAudit({actor,operation,phase:"failed",decisionId,referenceId,errorCode:"TASK_OPERATION_DENIED"});throw new TaskCenterError("TASK_OPERATION_DENIED");}await recordAudit({actor,operation,phase:"attempted",decisionId,referenceId});return{actor,decisionId};};
  const finish=async(context:{actor:TaskActor;decisionId:string},operation:TaskOperation,referenceId:string,error?:TaskCenterError):Promise<void>=>recordAudit({actor:context.actor,operation,phase:error===undefined?"succeeded":"failed",decisionId:context.decisionId,referenceId,...(error===undefined?{}:{errorCode:error.code})});
  const getAuthorized=async(actorInput:TaskActor,keyInput:TaskProjectionKey,operation:TaskOperation):Promise<TaskProjection>=>{const key=validateKey(keyInput);const context=await authorize(actorInput,operation,key);const referenceId=`${key.sourceType}:${key.sourceTaskId}`;try{const projection=await ports.store.get(key);if(!projection)throw new TaskCenterError("TASK_NOT_FOUND");await finish(context,operation,referenceId);return projection;}catch(error){const failure=mapped(error,"TASK_STORAGE_UNAVAILABLE");await finish(context,operation,referenceId,failure);throw failure;}};
  return {
    apply:(event,signal)=>observe("projection_apply",async()=>{try{return await ports.store.apply(validateEvent(event),signal);}catch(error){throw mapped(error,"TASK_STORAGE_UNAVAILABLE");}}),
    get:(actor,key)=>observe("task_detail",()=>getAuthorized(actor,key,"task_detail")),
    list:(query:TaskQuery)=>observe("task_list",async()=>{const actor=validateActor(query.actor);const context=await authorize(actor,"task_list");const limit=query.limit??50;if(!Number.isSafeInteger(limit)||limit<1||limit>100)throw new TaskCenterError("TASK_INPUT_INVALID");try{const page=await ports.store.list({limit,...(query.status===undefined?{}:{status:query.status}),...(query.cursor===undefined?{}:{cursor:query.cursor})});const items=[];for(const item of page.items){const key={sourceType:item.sourceType,sourceTaskId:item.sourceTaskId};try{const itemContext=await authorize(actor,"task_detail",key);await finish(itemContext,"task_detail",`${key.sourceType}:${key.sourceTaskId}`);items.push(item);}catch(error){if(!(error instanceof TaskCenterError)||error.code!=="TASK_OPERATION_DENIED")throw error;}}await finish(context,"task_list",actor.principalId);return{items,...(page.nextCursor===undefined?{}:{nextCursor:page.nextCursor})};}catch(error){const failure=mapped(error,"TASK_STORAGE_UNAVAILABLE");await finish(context,"task_list",actor.principalId,failure);throw failure;}}),
    complete:(input:CompleteTaskCommand)=>observe("task_complete",async()=>{const key=validateKey(input);const actor=validateActor(input.actor);const idempotencyKey=validateId(input.idempotencyKey);const sourceCommandReference=input.sourceCommandReference===undefined?undefined:validateId(input.sourceCommandReference);await getAuthorized(actor,key,"task_detail");const context=await authorize(actor,"task_complete",key);const referenceId=`${key.sourceType}:${key.sourceTaskId}`;const commandFingerprint=fingerprint({actor:actor.principalId,...key,...(sourceCommandReference===undefined?{}:{sourceCommandReference})});try{const claimedAt=now();if(!Number.isFinite(claimedAt))throw new TaskCenterError("TASK_STORAGE_UNAVAILABLE",{retryable:true});const leaseToken=validateUuid(commandLeaseToken());const claim=await ports.store.claimCommand({idempotencyKey,fingerprint:commandFingerprint,leaseToken,now:new Date(claimedAt),leaseExpiresAt:new Date(claimedAt+commandLeaseMs)});if(claim.status==="accepted"){await finish(context,"task_complete",referenceId);return claim.result;}if(claim.status==="running")throw new TaskCenterError("TASK_COMMAND_IN_PROGRESS",{retryable:true});let result;try{result=validateSourceCommandResult(await ports.router.complete({...key,actor,idempotencyKey,...(sourceCommandReference===undefined?{}:{sourceCommandReference})}));}catch(error){await ports.store.releaseCommand({idempotencyKey,leaseToken:claim.leaseToken});throw new TaskCenterError("TASK_SOURCE_UNAVAILABLE",{cause:error,retryable:true});}if(!await ports.store.acceptCommand({idempotencyKey,leaseToken:claim.leaseToken,result}))throw new TaskCenterError("TASK_COMMAND_IN_PROGRESS",{retryable:true});await finish(context,"task_complete",referenceId);return result;}catch(error){const failure=mapped(error,"TASK_STORAGE_UNAVAILABLE");await finish(context,"task_complete",referenceId,failure);throw failure;}}),
    reconcile:(actorInput,keyInput)=>observe("task_reconcile",async()=>{const key=validateKey(keyInput);const actor=validateActor(actorInput);const context=await authorize(actor,"task_reconcile",key);const referenceId=`${key.sourceType}:${key.sourceTaskId}`;try{const authoritative=validateEvent(await ports.sourceReader.get(key));if(authoritative.sourceType!==key.sourceType||authoritative.sourceTaskId!==key.sourceTaskId)throw new TaskCenterError("TASK_SOURCE_UNAVAILABLE",{retryable:true});const applied=await ports.store.reconcile(authoritative);const status:ReconciliationResult["status"]=applied.status==="applied"?"applied":applied.status==="duplicate"?"current":"stale";await finish(context,"task_reconcile",referenceId);return{status,projection:applied.projection};}catch(error){const failure=mapped(error,"TASK_SOURCE_UNAVAILABLE");await finish(context,"task_reconcile",referenceId,failure);throw failure;}}),
  };
};
