worker_processes 1;
pid /tmp/nginx/nginx.pid;

events { worker_connections 128; }

http {
  access_log off;
  error_log /dev/stderr warn;
  server_tokens off;
  client_body_temp_path /tmp/nginx/client;
  proxy_temp_path /tmp/nginx/proxy;
  fastcgi_temp_path /tmp/nginx/fastcgi;
  uwsgi_temp_path /tmp/nginx/uwsgi;
  scgi_temp_path /tmp/nginx/scgi;

  server {
    listen 8080;
    root /usr/share/nginx/html;
    location = /health/live {
      default_type application/json;
      return 200 '{"status":"ok"}';
    }
    location / {
      try_files $uri $uri/ /index.html;
    }
  }
}
