worker_processes 1;
pid /var/run/nginx.pid;

events { worker_connections 256; }

http {
  access_log /dev/stdout;
  error_log /dev/stderr warn;
  server_tokens off;

  upstream e2e_auth_bff { server host.docker.internal:13001; }
  server {
    listen 8080;
    root /usr/share/nginx/html;
    location = /health/live {
      access_log off;
      default_type application/json;
      return 200 '{"status":"ok"}';
    }
    location /auth/pc/ {
      proxy_pass http://e2e_auth_bff;
      proxy_http_version 1.1;
      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-Host $http_host;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
    location / {
      try_files $uri $uri/ /index.html;
    }
  }
}
