import { sql } from "drizzle-orm";
import { check, integer, jsonb, pgSchema, primaryKey, text, timestamp, uniqueIndex, uuid, varchar } from "drizzle-orm/pg-core";

const config = pgSchema("business_configuration");
export const dictionaryDrafts = config.table("dictionary_drafts", { dictionaryId: varchar("dictionary_id", { length: 128 }).primaryKey(), ownerModule: varchar("owner_module", { length: 128 }).notNull(), revision: integer("revision").notNull(), items: jsonb("items").notNull(), updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true }).notNull() }, (table) => [check("configuration_draft_revision_positive", sql`${table.revision}>0`)]);
export const dictionaryReleases = config.table("dictionary_releases", { dictionaryId: varchar("dictionary_id", { length: 128 }).notNull(), releaseVersion: integer("release_version").notNull(), ownerModule: varchar("owner_module", { length: 128 }).notNull(), contentDigest: varchar("content_digest", { length: 64 }).notNull(), items: jsonb("items").notNull(), publishedAt: timestamp("published_at", { mode: "string", withTimezone: true }).notNull() }, (table) => [primaryKey({ columns: [table.dictionaryId, table.releaseVersion] }), check("configuration_dictionary_version_positive", sql`${table.releaseVersion}>0`), check("configuration_dictionary_digest_length", sql`length(${table.contentDigest})=64`)]);
export const parameterDefinitions = config.table("parameter_definitions", { parameterKey: varchar("parameter_key", { length: 128 }).primaryKey(), definition: jsonb("definition").notNull() });
export const parameterValues = config.table("parameter_values", { parameterKey: varchar("parameter_key", { length: 128 }).notNull(), valueVersion: integer("value_version").notNull(), contentDigest: varchar("content_digest", { length: 64 }).notNull(), value: jsonb("value").notNull(), publishedAt: timestamp("published_at", { mode: "string", withTimezone: true }).notNull() }, (table) => [primaryKey({ columns: [table.parameterKey, table.valueVersion] }), check("configuration_value_version_positive", sql`${table.valueVersion}>0`), check("configuration_value_digest_length", sql`length(${table.contentDigest})=64`)]);
export const parameterActivations = config.table("parameter_activations", { activationId: uuid("activation_id").primaryKey(), parameterKey: varchar("parameter_key", { length: 128 }).notNull(), valueVersion: integer("value_version").notNull(), scopeType: varchar("scope_type", { length: 128 }).notNull(), scopeReference: varchar("scope_reference", { length: 255 }).notNull(), effectiveFrom: timestamp("effective_from", { mode: "string", withTimezone: true }).notNull(), effectiveTo: timestamp("effective_to", { mode: "string", withTimezone: true }) }, (table) => [uniqueIndex("configuration_activation_parameter_unique").on(table.activationId, table.parameterKey), check("configuration_activation_interval", sql`${table.effectiveTo} is null or ${table.effectiveFrom}<${table.effectiveTo}`)]);
export const parameterActivationTerminations = config.table("parameter_activation_terminations", { terminationId: uuid("termination_id").primaryKey(), activationId: uuid("activation_id").notNull(), parameterKey: varchar("parameter_key", { length: 128 }).notNull(), effectiveTo: timestamp("effective_to", { mode: "string", withTimezone: true }).notNull(), occurredAt: timestamp("occurred_at", { mode: "string", withTimezone: true }).notNull() }, (table) => [uniqueIndex("configuration_activation_termination_unique").on(table.activationId), check("configuration_termination_not_backdated", sql`${table.effectiveTo}>=${table.occurredAt}`)]);
export const receipts = config.table("operation_receipts", { operationId: uuid("operation_id").primaryKey(), fingerprint: varchar("fingerprint", { length: 64 }).notNull(), result: jsonb("result").notNull() });
export const outbox = config.table("outbox_events", { eventId: uuid("event_id").primaryKey(), eventType: varchar("event_type", { length: 80 }).notNull(), resourceId: varchar("resource_id", { length: 128 }).notNull(), resourceVersion: integer("resource_version").notNull(), occurredAt: timestamp("occurred_at", { mode: "string", withTimezone: true }).notNull(), publishedAt: timestamp("published_at", { mode: "string", withTimezone: true }), lastError: text("last_error") }, (table) => [check("configuration_outbox_version_nonnegative", sql`${table.resourceVersion}>=0`)]);
