import{createHash}from"node:crypto";import{Ajv2020,type ValidateFunction}from"ajv/dist/2020.js";import{BusinessConfigurationError}from"./errors.js";import type{ConfigurationActor,ConfigurationValue,DictionaryItem,ParameterDefinition,ParameterScope}from"./types.js";
const ID=/^[a-z][a-z0-9_.-]{0,127}$/u,REF=/^[A-Za-z0-9_.:@/-]{1,255}$/u,UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/iu,TRACE=/^(?!0{32})[0-9a-f]{32}$/u,SENSITIVE=/(credential|password|secret|session|token)/iu,SECRET_VALUE=/(?:-----BEGIN|Bearer\s|postgres(?:ql)?:\/\/|AKID[A-Z0-9]{8})/iu;
const invalid=(code:"configuration_invalid_input"|"configuration_missing"="configuration_invalid_input"):never=>{throw new BusinessConfigurationError(code)};const object=(v:unknown):Record<string,unknown>=>typeof v==="object"&&v!==null&&!Array.isArray(v)?v as Record<string,unknown>:invalid();const exact=(v:unknown,req:readonly string[],opt:readonly string[]=[]):Record<string,unknown>=>{const o=object(v);const keys=Object.keys(o);if(req.some(k=>!Object.hasOwn(o,k))||keys.some(k=>!req.includes(k)&&!opt.includes(k)))invalid();return o};const array=(v:unknown,max:number):unknown[]=>{if(!Array.isArray(v)||v.length>max)invalid();return v as unknown[]};export const id=(v:unknown):string=>typeof v==="string"&&ID.test(v)&&!SENSITIVE.test(v)?v:invalid();export const uuid=(v:unknown):string=>typeof v==="string"&&UUID.test(v)?v.toLowerCase():invalid();export const version=(v:unknown,zero=false):number=>Number.isSafeInteger(v)&&(v as number)>=(zero?0:1)?v as number:invalid();export const date=(v:unknown):string=>typeof v==="string"&&Number.isFinite(Date.parse(v))&&new Date(v).toISOString()===v?v:invalid();
export function actor(v:unknown):ConfigurationActor{const o=exact(v,["actorId","actorType"],["assignmentId"]);const actorType=o.actorType==="authenticated_subject"||o.actorType==="system"?o.actorType:invalid();return{actorId:typeof o.actorId==="string"&&REF.test(o.actorId)?o.actorId:invalid(),actorType,...(o.assignmentId===undefined?{}:{assignmentId:uuid(o.assignmentId)})}}
export function command(v:unknown,fields:readonly string[]){const values=exact(v,["actor","operationId","reason","traceId",...fields]);return{actor:actor(values.actor),operationId:uuid(values.operationId),reason:typeof values.reason==="string"&&values.reason.length>=1&&values.reason.length<=500?values.reason:invalid(),traceId:typeof values.traceId==="string"&&TRACE.test(values.traceId)?values.traceId:invalid(),values}}
export function decision(v:unknown){const o=exact(v,["allowed","decisionId"]);const allowed=typeof o.allowed==="boolean"?o.allowed:invalid();return{allowed,decisionId:uuid(o.decisionId)}}
export function itemList(v:unknown):readonly DictionaryItem[]{const seen=new Set<string>();return array(v,500).map(x=>{const o=exact(x,["code","enabled","label","order"]);const code=id(o.code);if(seen.has(code))invalid();seen.add(code);const enabled=typeof o.enabled==="boolean"?o.enabled:invalid();const label=typeof o.label==="string"&&o.label.length>=1&&o.label.length<=200&&!/[<>]/u.test(o.label)?o.label:invalid();const order=Number.isSafeInteger(o.order)&&(o.order as number)>=0&&(o.order as number)<=100000?o.order as number:invalid();return{code,enabled,label,order}})}
export function scope(v:unknown):ParameterScope{const o=exact(v,["scopeReference","scopeType"]);return{scopeReference:typeof o.scopeReference==="string"&&REF.test(o.scopeReference)?o.scopeReference:invalid(),scopeType:id(o.scopeType)}}
export function definition(v:unknown):ParameterDefinition{const o=exact(v,["allowedScopes","missingPolicy","ownerModule","parameterKey","valueSchema","valueType"],["defaultValue"]);const valueType=["boolean","integer","number","string"].includes(String(o.valueType))?o.valueType as ParameterDefinition["valueType"]:invalid();const schema=exact(o.valueSchema,["$schema","type"],["enum","maxLength","maximum","minLength","minimum"]);if(schema.$schema!=="https://json-schema.org/draft/2020-12/schema"||schema.type!==valueType)invalid();for(const key of Object.keys(schema))if(!["$schema","type","enum","maxLength","maximum","minLength","minimum"].includes(key))invalid();const priorities=new Set<number>(),scopeTypes=new Set<string>();const allowedScopes=array(o.allowedScopes,20).map(x=>{const s=exact(x,["priority","scopeType"]);const priority=Number.isSafeInteger(s.priority)&&(s.priority as number)>=0&&(s.priority as number)<=1000?s.priority as number:invalid();const scopeType=id(s.scopeType);if(priorities.has(priority)||scopeTypes.has(scopeType))invalid();priorities.add(priority);scopeTypes.add(scopeType);return{priority,scopeType}});if(allowedScopes.length===0)invalid();const missingPolicy:ParameterDefinition["missingPolicy"]=o.missingPolicy==="fail_closed"||o.missingPolicy==="use_default"?o.missingPolicy:invalid();const ownerModule=id(o.ownerModule),parameterKey=id(o.parameterKey);const result:ParameterDefinition={allowedScopes,definitionVersion:1,missingPolicy,ownerModule,parameterKey,valueSchema:structuredClone(schema),valueType,...(o.defaultValue===undefined?{}:{defaultValue:value(o.defaultValue,valueType)})};if(missingPolicy==="use_default"&&result.defaultValue===undefined)invalid();if(missingPolicy==="fail_closed"&&result.defaultValue!==undefined)invalid();if(result.defaultValue!==undefined&&!compile(result)(result.defaultValue))invalid();return result}
export function value(v:unknown,type:ParameterDefinition["valueType"]):ConfigurationValue{if((type==="string"&&typeof v==="string"&&!SECRET_VALUE.test(v)&&v.length<=1000)||(type==="boolean"&&typeof v==="boolean")||(type==="number"&&typeof v==="number"&&Number.isFinite(v))||(type==="integer"&&Number.isSafeInteger(v)))return v as ConfigurationValue;return invalid()}
export function compile(d:Pick<ParameterDefinition,"valueSchema">):ValidateFunction{try{return new Ajv2020({strict:true}).compile(d.valueSchema)}catch(error){throw new BusinessConfigurationError("configuration_invalid_input",{cause:error})}}
const canonical=(v:unknown):string=>Array.isArray(v)?`[${v.map(canonical).join(",")}]`:typeof v==="object"&&v!==null?`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonical((v as Record<string,unknown>)[k])}`).join(",")}}`:JSON.stringify(v);export const hash=(v:unknown):string=>createHash("sha256").update(canonical(v)).digest("hex");
