import { randomUUID } from "node:crypto";
import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { createDatabaseRuntime, runMigrations, type DatabaseRuntime } from "@ai-crm/database";
import { afterAll, beforeAll, describe, expect, it, vi } from "vitest";
import { createFileCenterService, createPrismaFileCenterStore, type FileAudit, type FileAuthorizer, type MalwareScanner, type StorageAdapter, type StorageObjectMetadata } from "./index.js";

const urlFile = process.env.TEST_FILE_CENTER_DATABASE_URL_FILE;
const suite = describe.skipIf(!urlFile);
suite("PostgreSQL File Center", () => {
  let runtime: DatabaseRuntime | undefined;
  beforeAll(async () => { if (!urlFile) throw new Error("TEST_FILE_CENTER_DATABASE_URL_FILE is required."); const connectionString = (await readFile(resolve(urlFile), "utf8")).trim(); await runMigrations(connectionString, resolve(import.meta.dirname, "../../../database/migrations")); await runMigrations(connectionString, resolve(import.meta.dirname, "../migrations")); runtime = createDatabaseRuntime({ applicationName: "plt_03_file_test", connectionString, connectionTimeoutMs: 5_000, idleTimeoutMs: 5_000, maxConnections: 8, statementTimeoutMs: 5_000 }); });
  afterAll(async () => runtime?.close());

  it("commits upload, scan, link and outbox facts atomically and guards immutable fields", async () => {
    if (!runtime) throw new Error("runtime unavailable"); const fixture = setup(runtime); const created = await fixture.create(); fixture.storage.objects.set(fixture.storage.handle, new TextEncoder().encode("fixture")); const completed = await fixture.service.completeUpload({ ...meta(), sessionId: created.session.sessionId }); const scanned = await fixture.service.scanContentVersion({ ...meta(), contentVersionId: completed.contentVersion.contentVersionId }); expect(scanned.contentVersion.status).toBe("available"); const link = await fixture.service.linkResource({ ...meta(), fileReference: created.fileReference, linkId: randomUUID(), ownerModule: "crm.synthetic", relationType: "crm.attachment", resource: { resourceId: "synthetic:1", resourceType: "crm.resource" } });
    const evidence = await runtime.execute<{ event_count: number; receipt_count: number }>("select (select count(*)::int from file_center.outbox_events where resource_id=$1) event_count,(select count(*)::int from file_center.operation_receipts) receipt_count", [created.fileReference.fileId]); expect(evidence.rows[0]?.event_count).toBe(3); expect(evidence.rows[0]?.receipt_count).toBe(4);
    await expect(runtime.execute("update file_center.content_versions set object_handle='objects/changed/value' where content_version_id=$1", [created.fileReference.contentVersionId])).rejects.toMatchObject({ code: "55000" }); await expect(runtime.execute("delete from file_center.files where file_id=$1", [created.fileReference.fileId])).rejects.toMatchObject({ code: "55000" }); await expect(runtime.execute("update file_center.resource_links set resource_id='changed' where link_id=$1", [link.link.linkId])).rejects.toMatchObject({ code: "55000" });
  });

  it("serializes duplicate upload operations without duplicate metadata", async () => {
    if (!runtime) throw new Error("runtime unavailable"); const fixture = setup(runtime); const operationId = randomUUID(); const [first, second] = await Promise.all([fixture.create(operationId), fixture.create(operationId)]); expect([first.replayed, second.replayed].sort()).toEqual([false, true]); expect(first.fileReference).toEqual(second.fileReference); const count = await runtime.execute<{ count: number }>("select count(*)::int count from file_center.files where file_id=$1", [first.fileReference.fileId]); expect(count.rows[0]?.count).toBe(1);
  });

  it("serializes immutable content-version allocation and replays the assigned version", async () => {
    if (!runtime) throw new Error("runtime unavailable"); const fixture = setup(runtime); const original = await fixture.create(); const operationId = randomUUID();
    const createVersion = (id = randomUUID()) => fixture.service.createContentVersionUpload({ ...meta(), declaredMediaType: "text/plain", declaredSizeBytes: 7, fileId: original.fileReference.fileId, operationId: id });
    const [second, third] = await Promise.all([createVersion(operationId), createVersion()]); const replay = await createVersion(operationId);
    const rows = await runtime.execute<{ content_version_id: string; version_number: number }>("select content_version_id,version_number from file_center.content_versions where file_id=$1 order by version_number", [original.fileReference.fileId]);
    expect(rows.rows.map((row) => row.version_number)).toEqual([1, 2, 3]); expect(new Set(rows.rows.map((row) => row.content_version_id)).size).toBe(3); expect(replay).toMatchObject({ fileReference: second.fileReference, replayed: true });
    await expect(runtime.execute("update file_center.content_versions set version_number=99 where content_version_id=$1", [second.fileReference.contentVersionId])).rejects.toMatchObject({ code: "55000" }); expect(third.fileReference.contentVersionId).not.toBe(second.fileReference.contentVersionId);
  });

  it("persists cleanup_pending across a storage failure and completes on replay", async () => {
    if (!runtime) throw new Error("runtime unavailable"); const fixture = setup(runtime); const created = await fixture.create(); fixture.storage.failDelete = true; fixture.setNow(new Date("2026-07-26T10:02:00.000Z")); const command = { ...meta(), sessionId: created.session.sessionId }; await expect(fixture.service.cleanupUploadSession(command)).rejects.toMatchObject({ code: "file_center_storage_unavailable" }); const pending = await runtime.execute<{ status: string }>("select status from file_center.upload_sessions where session_id=$1", [created.session.sessionId]); expect(pending.rows[0]?.status).toBe("cleanup_pending"); fixture.storage.failDelete = false; await expect(fixture.service.cleanupUploadSession(command)).resolves.toMatchObject({ cleaned: true, replayed: true });
  });

  it("protects coordination states, validates cleanup transitions, and enforces the completion cutoff", async () => {
    if (!runtime) throw new Error("runtime unavailable"); const fixture = setup(runtime); const created = await fixture.create(); const store = createPrismaFileCenterStore(runtime);
    await expect(store.completeUpload({ completedAt: created.session.expiresAt, event: { eventId: randomUUID(), eventType: "file.upload.completed", occurredAt: created.session.expiresAt, resourceId: created.fileReference.fileId, version: 1 }, fingerprint: "c".repeat(64), operationId: randomUUID(), sessionId: created.session.sessionId, sizeBytes: 7 })).rejects.toMatchObject({ code: "file_center_operation_conflict" });
    let state = await runtime.execute<{ session_status: string; version_status: string }>("select s.status session_status,v.status version_status from file_center.upload_sessions s join file_center.content_versions v using(content_version_id) where s.session_id=$1", [created.session.sessionId]); expect(state.rows[0]).toEqual({ session_status: "created", version_status: "awaiting_upload" });
    await runtime.execute("update file_center.content_versions set status='quarantine_pending' where content_version_id=$1", [created.fileReference.contentVersionId]); const reconciled = await store.markReconciled({ contentVersionId: created.fileReference.contentVersionId, fingerprint: "d".repeat(64), objectExists: false, operationId: randomUUID() }); expect(reconciled.contentVersion.status).toBe("quarantine_pending");
    await runtime.execute("update file_center.content_versions set status='cleanup_pending' where content_version_id=$1", [created.fileReference.contentVersionId]); await runtime.execute("update file_center.upload_sessions set status='cleanup_pending' where session_id=$1", [created.session.sessionId]); await runtime.execute("update file_center.content_versions set status='object_missing' where content_version_id=$1", [created.fileReference.contentVersionId]); await expect(store.completeCleanup(created.session.sessionId)).rejects.toMatchObject({ code: "file_center_operation_conflict" }); state = await runtime.execute<{ session_status: string; version_status: string }>("select s.status session_status,v.status version_status from file_center.upload_sessions s join file_center.content_versions v using(content_version_id) where s.session_id=$1", [created.session.sessionId]); expect(state.rows[0]).toEqual({ session_status: "cleanup_pending", version_status: "object_missing" });
  });
});

const actor = { actorId: "system.synthetic", actorType: "system" as const }; const traceId = "1234567890abcdef1234567890abcdef"; const meta = () => ({ actor, operationId: randomUUID(), reason: "synthetic integration", traceId });
class Storage implements StorageAdapter { handle = ""; objects = new Map<string, Uint8Array>(); failDelete = false; createUploadGrant(input: Parameters<StorageAdapter["createUploadGrant"]>[0]) { this.handle = input.objectHandle; return Promise.resolve({ url: "https://upload.invalid/grant" }); } createDownloadGrant() { return Promise.resolve({ url: "https://download.invalid/grant" }); } inspectObject({ objectHandle }: { readonly objectHandle: string }): Promise<StorageObjectMetadata> { const bytes = this.objects.get(objectHandle); return Promise.resolve(bytes ? { checksumSha256: "a".repeat(64), detectedMediaType: "text/plain", exists: true, sizeBytes: bytes.byteLength } : { exists: false }); } readObject({ maximumBytes, objectHandle }: Parameters<StorageAdapter["readObject"]>[0]) { const bytes = this.objects.get(objectHandle); if (!bytes) return Promise.reject(new Error("missing")); return bytes.byteLength <= maximumBytes ? Promise.resolve(bytes) : Promise.reject(new Error("bounded read rejected")); } quarantineObject() { return Promise.resolve(); } deleteObject({ objectHandle }: { readonly objectHandle: string }) { if (this.failDelete) return Promise.reject(new Error("delete failure")); this.objects.delete(objectHandle); return Promise.resolve(); } }
function setup(runtime: DatabaseRuntime) { let current = new Date("2026-07-26T10:00:00.000Z"); const storage = new Storage(); const service = createFileCenterService(createPrismaFileCenterStore(runtime), storage, { scan: vi.fn<MalwareScanner["scan"]>(() => Promise.resolve({ outcome: "clean", scannerVersion: "synthetic.v1" })) }, { authorize: vi.fn<FileAuthorizer["authorize"]>(() => Promise.resolve({ allowed: true, decisionId: randomUUID() })) }, { record: vi.fn<FileAudit["record"]>(() => Promise.resolve()) }, { clock: () => current, downloadGrantTtlMs: 60_000, maximumScanBytes: 1024, maximumUploadBytes: 1024, uploadSessionTtlMs: 60_000 }); return { create: (operationId = randomUUID()) => service.createUploadSession({ ...meta(), declaredMediaType: "text/plain", declaredSizeBytes: 7, displayName: "synthetic.txt", operationId, ownerModule: "crm.synthetic" }), service, setNow: (value: Date) => { current = value; }, storage }; }
