/* eslint-disable @typescript-eslint/no-non-null-assertion */
import { createHash } from "node:crypto";
import type { OrganizationDirectoryCommit, OrganizationDirectoryMutation, OrganizationDirectoryStore } from "./directory-store.js";
import type { CreateDepartmentCommand, CreateDirectoryPositionCommand, DepartmentDirectoryEntry, DepartmentTreeNode, OrganizationDirectoryAuthorizer, OrganizationDirectoryMetadata, OrganizationDirectoryServiceApi, PositionDirectoryEntry, SetDepartmentActiveCommand, SetPositionActiveCommand, UpdateDepartmentCommand, UpdateDirectoryPositionCommand, UpsertWorkforcePersonProfileCommand, WorkforcePersonProfile } from "./directory-types.js";
import { OrganizationError } from "./errors.js";
import { requireId, requireText, requireTimestamp } from "./validation.js";

const normalizeName = (value: string): string => { requireText(value, 100); return value.trim().toLocaleLowerCase("zh-CN"); };
export class OrganizationDirectoryService implements OrganizationDirectoryServiceApi {
  constructor(private readonly store: OrganizationDirectoryStore, private readonly authorizer: OrganizationDirectoryAuthorizer) {}
  async upsertPersonProfile(command: UpsertWorkforcePersonProfileCommand): Promise<WorkforcePersonProfile> { this.#metadata(command); requireId(command.workforcePersonId); requireTimestamp(command.updatedAt); const realName = command.realName.trim(); requireText(realName, 100); const current = await this.store.findPersonProfile(command.workforcePersonId); if ((current?.revision ?? undefined) !== command.expectedRevision) throw new OrganizationError("entity_conflict"); await this.#authorize(command, "workforce_person_profile_updated", "workforce_person_profile", command.workforcePersonId); const profile = { workforcePersonId: command.workforcePersonId, realName, revision: (current?.revision ?? -1) + 1, updatedAt: command.updatedAt }; await this.#commit(command, { expectedRevision: command.expectedRevision, kind: "upsert_person_profile", profile }); return (await this.store.findPersonProfile(command.workforcePersonId))!; }
  async createDepartment(command: CreateDepartmentCommand): Promise<DepartmentDirectoryEntry> { this.#metadata(command); requireId(command.organizationUnitId); requireTimestamp(command.updatedAt); const normalizedName = normalizeName(command.name); if (command.parentOrganizationUnitId) { requireId(command.parentOrganizationUnitId); const parent = await this.#department(command.parentOrganizationUnitId); if (!parent.active) throw new OrganizationError("organization_path_invalid"); } await this.#authorize(command, "department_created", "department", command.organizationUnitId); const department = { active: true, name: command.name.trim(), normalizedName, organizationUnitId: command.organizationUnitId, ...(command.parentOrganizationUnitId ? { parentOrganizationUnitId: command.parentOrganizationUnitId } : {}), revision: 0, rootLocked: command.rootLocked ?? false, updatedAt: command.updatedAt }; await this.#commit(command, { department, kind: "create_department" }); return this.#department(command.organizationUnitId); }
  async updateDepartment(command: UpdateDepartmentCommand): Promise<DepartmentDirectoryEntry> { this.#metadata(command); requireId(command.organizationUnitId); requireTimestamp(command.updatedAt); const current = await this.#department(command.organizationUnitId); if (command.name === undefined && command.parentOrganizationUnitId === undefined) throw new OrganizationError("entity_conflict"); if (current.rootLocked && command.parentOrganizationUnitId !== undefined) throw new OrganizationError("entity_conflict"); const normalizedName = command.name === undefined ? undefined : normalizeName(command.name); if (command.parentOrganizationUnitId) { requireId(command.parentOrganizationUnitId); const parent = await this.#department(command.parentOrganizationUnitId); if (!parent.active) throw new OrganizationError("organization_path_invalid"); await this.#noCycle(command.organizationUnitId, command.parentOrganizationUnitId); } await this.#authorize(command, "department_updated", "department", command.organizationUnitId); await this.#commit(command, { departmentId: command.organizationUnitId, expectedRevision: command.expectedRevision, kind: "update_department", ...(command.name === undefined ? {} : { name: command.name.trim(), normalizedName }), ...(command.parentOrganizationUnitId === undefined ? {} : { parentOrganizationUnitId: command.parentOrganizationUnitId }), updatedAt: command.updatedAt }); return this.#department(command.organizationUnitId); }
  async setDepartmentActive(command: SetDepartmentActiveCommand): Promise<DepartmentDirectoryEntry> { this.#metadata(command); requireId(command.organizationUnitId); requireTimestamp(command.updatedAt); const current = await this.#department(command.organizationUnitId); if (!command.active) { if (current.rootLocked) throw new OrganizationError("entity_conflict"); const [departments, positions, assigned] = await Promise.all([this.store.listDepartments(), this.store.listPositions(command.organizationUnitId), this.store.hasActiveAssignmentReferences({ organizationUnitId: command.organizationUnitId })]); if (departments.some((item) => item.active && item.parentOrganizationUnitId === command.organizationUnitId) || positions.some((item) => item.active) || assigned) throw new OrganizationError("entity_conflict"); } else if (current.parentOrganizationUnitId && !(await this.#department(current.parentOrganizationUnitId)).active) throw new OrganizationError("organization_path_invalid"); await this.#authorize(command, command.active ? "department_restored" : "department_disabled", "department", command.organizationUnitId); await this.#commit(command, { active: command.active, departmentId: command.organizationUnitId, expectedRevision: command.expectedRevision, kind: "set_department_active", updatedAt: command.updatedAt }); return this.#department(command.organizationUnitId); }
  async createPosition(command: CreateDirectoryPositionCommand): Promise<PositionDirectoryEntry> { this.#metadata(command); requireId(command.positionId); requireId(command.organizationUnitId); requireTimestamp(command.updatedAt); const department = await this.#department(command.organizationUnitId); if (!department.active) throw new OrganizationError("organization_path_invalid"); const normalizedName = normalizeName(command.name); await this.#authorize(command, "position_directory_created", "position", command.positionId); const position = { active: true, name: command.name.trim(), normalizedName, organizationUnitId: command.organizationUnitId, positionId: command.positionId, revision: 0, updatedAt: command.updatedAt }; await this.#commit(command, { kind: "create_position", position }); return this.#position(command.positionId); }
  async updatePosition(command: UpdateDirectoryPositionCommand): Promise<PositionDirectoryEntry> { this.#metadata(command); requireId(command.positionId); requireTimestamp(command.updatedAt); await this.#position(command.positionId); const normalizedName = normalizeName(command.name); await this.#authorize(command, "position_directory_updated", "position", command.positionId); await this.#commit(command, { expectedRevision: command.expectedRevision, kind: "update_position", name: command.name.trim(), normalizedName, positionId: command.positionId, updatedAt: command.updatedAt }); return this.#position(command.positionId); }
  async setPositionActive(command: SetPositionActiveCommand): Promise<PositionDirectoryEntry> { this.#metadata(command); requireId(command.positionId); requireTimestamp(command.updatedAt); const current = await this.#position(command.positionId); if (!command.active && await this.store.hasActiveAssignmentReferences({ positionId: command.positionId })) throw new OrganizationError("entity_conflict"); if (command.active && !(await this.#department(current.organizationUnitId)).active) throw new OrganizationError("organization_path_invalid"); await this.#authorize(command, command.active ? "position_restored" : "position_disabled", "position", command.positionId); await this.#commit(command, { active: command.active, expectedRevision: command.expectedRevision, kind: "set_position_active", positionId: command.positionId, updatedAt: command.updatedAt }); return this.#position(command.positionId); }
  async getPersonProfile(id: string): Promise<WorkforcePersonProfile> { requireId(id); const value = await this.store.findPersonProfile(id); if (!value) throw new OrganizationError("entity_not_found"); return value; }
  async listPositions(id: string, input?: { readonly includeInactive?: boolean }): Promise<readonly PositionDirectoryEntry[]> { requireId(id); return (await this.store.listPositions(id)).filter((item) => input?.includeInactive || item.active).sort((a, b) => a.name.localeCompare(b.name, "zh-CN")); }
  async listDepartmentTree(input?: { readonly includeInactive?: boolean }): Promise<readonly DepartmentTreeNode[]> { const rows = (await this.store.listDepartments()).filter((item) => input?.includeInactive || item.active); const build = (parent?: string): DepartmentTreeNode[] => rows.filter((item) => item.parentOrganizationUnitId === parent).sort((a, b) => a.name.localeCompare(b.name, "zh-CN")).map((item) => ({ ...item, children: build(item.organizationUnitId) })); return build(); }
  async #noCycle(id: string, parentId: string): Promise<void> { const visited = new Set([id]); let current: string | undefined = parentId; while (current) { if (visited.has(current)) throw new OrganizationError("organization_hierarchy_cycle"); visited.add(current); current = (await this.#department(current)).parentOrganizationUnitId; } }
  async #department(id: string): Promise<DepartmentDirectoryEntry> { const value = await this.store.findDepartment(id); if (!value) throw new OrganizationError("entity_not_found"); return value; }
  async #position(id: string): Promise<PositionDirectoryEntry> { const value = await this.store.findPosition(id); if (!value) throw new OrganizationError("entity_not_found"); return value; }
  #metadata(command: OrganizationDirectoryMetadata): void { requireId(command.operationId); requireText(command.actor.actorId); requireText(command.reason, 500); requireText(command.traceId, 128); }
  #authorize(command: OrganizationDirectoryMetadata, action: string, entityType: "department" | "position" | "workforce_person_profile", entityId: string): Promise<void> { return this.authorizer.authorize({ action, actor: command.actor, entityId, entityType, operationId: command.operationId }); }
  #commit(command: OrganizationDirectoryMetadata, mutation: OrganizationDirectoryMutation): Promise<{ readonly replayed: boolean }> { const { operationId, traceId, ...request } = command; void traceId; const fingerprint = createHash("sha256").update(JSON.stringify(request)).digest("hex"); const commit: OrganizationDirectoryCommit = { fingerprint, mutation, operationId }; return this.store.commit(commit); }
}
