/* eslint-disable @typescript-eslint/no-non-null-assertion */
import type { DatabaseRuntime } from "@ai-crm/database";
import type { OrganizationDirectoryCommit, OrganizationDirectoryMutation, OrganizationDirectoryStore } from "./directory-store.js";
import type { DepartmentDirectoryEntry, PositionDirectoryEntry, WorkforcePersonProfile } from "./directory-types.js";
import { OrganizationError } from "./errors.js";

export type OrganizationDirectoryPersistenceRuntime = Pick<DatabaseRuntime, "execute" | "withTransaction">;
interface DepartmentRow { organization_unit_id: string; name: string; normalized_name: string; parent_organization_unit_id: string | null; active: boolean; root_locked: boolean; revision: number; updated_at: Date | string }
interface PositionRow { position_id: string; organization_unit_id: string; name: string; normalized_name: string; active: boolean; revision: number; updated_at: Date | string }
interface ProfileRow { workforce_person_id: string; real_name: string; revision: number; updated_at: Date | string }
const iso = (v: Date | string): string => v instanceof Date ? v.toISOString() : new Date(v).toISOString();
const department = (r: DepartmentRow): DepartmentDirectoryEntry => ({ active: r.active, name: r.name, normalizedName: r.normalized_name, organizationUnitId: r.organization_unit_id, ...(r.parent_organization_unit_id ? { parentOrganizationUnitId: r.parent_organization_unit_id } : {}), revision: r.revision, rootLocked: r.root_locked, updatedAt: iso(r.updated_at) });
const position = (r: PositionRow): PositionDirectoryEntry => ({ active: r.active, name: r.name, normalizedName: r.normalized_name, organizationUnitId: r.organization_unit_id, positionId: r.position_id, revision: r.revision, updatedAt: iso(r.updated_at) });
const profile = (r: ProfileRow): WorkforcePersonProfile => ({ realName: r.real_name, revision: r.revision, updatedAt: iso(r.updated_at), workforcePersonId: r.workforce_person_id });

class PrismaOrganizationDirectoryStore implements OrganizationDirectoryStore {
  constructor(private readonly db: OrganizationDirectoryPersistenceRuntime) {}
  commit(command: OrganizationDirectoryCommit): Promise<{ readonly replayed: boolean }> { return this.db.withTransaction(async () => { const claimed = await this.db.execute<{ fingerprint: string }>("insert into organization.directory_operation_receipts (operation_id,fingerprint) values ($1,$2) on conflict (operation_id) do nothing returning fingerprint", [command.operationId, command.fingerprint]); if (claimed.rowCount === 0) { const prior = await this.db.execute<{ fingerprint: string }>("select fingerprint from organization.directory_operation_receipts where operation_id=$1", [command.operationId]); if (prior.rows[0]?.fingerprint !== command.fingerprint) throw new OrganizationError("idempotency_conflict"); return { replayed: true }; } try { await this.#apply(command.mutation); } catch (error) { const code = (error as { code?: string }).code; if (code === "23503") throw new OrganizationError("entity_not_found"); if (code === "23505" || code === "23514") throw new OrganizationError("entity_conflict"); throw error; } return { replayed: false }; }); }
  async findDepartment(id: string): Promise<DepartmentDirectoryEntry | undefined> { const r = await this.db.execute<DepartmentRow>("select * from organization.department_directory where organization_unit_id=$1", [id]); return r.rows[0] ? department(r.rows[0]) : undefined; }
  async findPersonProfile(id: string): Promise<WorkforcePersonProfile | undefined> { const r = await this.db.execute<ProfileRow>("select * from organization.workforce_person_profiles where workforce_person_id=$1", [id]); return r.rows[0] ? profile(r.rows[0]) : undefined; }
  async findPosition(id: string): Promise<PositionDirectoryEntry | undefined> { const r = await this.db.execute<PositionRow>("select * from organization.position_directory where position_id=$1", [id]); return r.rows[0] ? position(r.rows[0]) : undefined; }
  async hasActiveAssignmentReferences(input: { readonly organizationUnitId?: string; readonly positionId?: string }): Promise<boolean> { const r = await this.db.execute<{ exists: boolean }>("select exists(select 1 from organization.assignments where effective_to is null and ($1::uuid is null or organization_unit_id=$1) and ($2::uuid is null or position_id=$2)) as exists", [input.organizationUnitId ?? null, input.positionId ?? null]); return r.rows[0]?.exists ?? false; }
  async listDepartments(): Promise<readonly DepartmentDirectoryEntry[]> { const r = await this.db.execute<DepartmentRow>("select * from organization.department_directory order by organization_unit_id"); return r.rows.map(department); }
  async listPositions(id: string): Promise<readonly PositionDirectoryEntry[]> { const r = await this.db.execute<PositionRow>("select * from organization.position_directory where organization_unit_id=$1 order by position_id", [id]); return r.rows.map(position); }
  async #apply(m: OrganizationDirectoryMutation): Promise<void> {
    if (m.kind === "upsert_person_profile") { const result = m.expectedRevision === undefined ? await this.db.execute("insert into organization.workforce_person_profiles (workforce_person_id,real_name,revision,updated_at) values ($1,$2,$3,$4) on conflict do nothing", [m.profile.workforcePersonId, m.profile.realName, m.profile.revision, m.profile.updatedAt]) : await this.db.execute("update organization.workforce_person_profiles set real_name=$3,revision=revision+1,updated_at=$4 where workforce_person_id=$1 and revision=$2", [m.profile.workforcePersonId, m.expectedRevision, m.profile.realName, m.profile.updatedAt]); this.#revision(result.rowCount); await this.db.execute("insert into organization.workforce_person_profile_history (workforce_person_id,revision,real_name,recorded_at) values ($1,$2,$3,$4)", [m.profile.workforcePersonId, m.profile.revision, m.profile.realName, m.profile.updatedAt]); return; }
    if (m.kind === "create_department") { await this.db.execute("insert into organization.department_directory (organization_unit_id,name,normalized_name,parent_organization_unit_id,active,root_locked,revision,updated_at) values ($1,$2,$3,$4,$5,$6,$7,$8)", [m.department.organizationUnitId, m.department.name, m.department.normalizedName, m.department.parentOrganizationUnitId ?? null, m.department.active, m.department.rootLocked, m.department.revision, m.department.updatedAt]); await this.#departmentHistory(m.department); return; }
    if (m.kind === "update_department") { const result = await this.db.execute("update organization.department_directory set name=coalesce($3,name),normalized_name=coalesce($4,normalized_name),parent_organization_unit_id=case when $5::boolean then $6 else parent_organization_unit_id end,revision=revision+1,updated_at=$7 where organization_unit_id=$1 and revision=$2", [m.departmentId, m.expectedRevision, m.name ?? null, m.normalizedName ?? null, m.parentOrganizationUnitId !== undefined, m.parentOrganizationUnitId ?? null, m.updatedAt]); this.#revision(result.rowCount); await this.#departmentHistory((await this.findDepartment(m.departmentId))!); return; }
    if (m.kind === "set_department_active") { const result = await this.db.execute("update organization.department_directory set active=$3,revision=revision+1,updated_at=$4 where organization_unit_id=$1 and revision=$2", [m.departmentId, m.expectedRevision, m.active, m.updatedAt]); this.#revision(result.rowCount); await this.#departmentHistory((await this.findDepartment(m.departmentId))!); return; }
    if (m.kind === "create_position") { await this.db.execute("insert into organization.position_directory (position_id,organization_unit_id,name,normalized_name,active,revision,updated_at) values ($1,$2,$3,$4,$5,$6,$7)", [m.position.positionId, m.position.organizationUnitId, m.position.name, m.position.normalizedName, m.position.active, m.position.revision, m.position.updatedAt]); await this.#positionHistory(m.position); return; }
    if (m.kind === "update_position") { const result = await this.db.execute("update organization.position_directory set name=$3,normalized_name=$4,revision=revision+1,updated_at=$5 where position_id=$1 and revision=$2", [m.positionId, m.expectedRevision, m.name, m.normalizedName, m.updatedAt]); this.#revision(result.rowCount); await this.#positionHistory((await this.findPosition(m.positionId))!); return; }
    const result = await this.db.execute("update organization.position_directory set active=$3,revision=revision+1,updated_at=$4 where position_id=$1 and revision=$2", [m.positionId, m.expectedRevision, m.active, m.updatedAt]); this.#revision(result.rowCount); await this.#positionHistory((await this.findPosition(m.positionId))!);
  }
  #revision(count: number): void { if (count !== 1) throw new OrganizationError("entity_conflict"); }
  async #departmentHistory(v: DepartmentDirectoryEntry): Promise<void> { await this.db.execute("insert into organization.department_directory_history (organization_unit_id,revision,name,parent_organization_unit_id,active,recorded_at) values ($1,$2,$3,$4,$5,$6)", [v.organizationUnitId, v.revision, v.name, v.parentOrganizationUnitId ?? null, v.active, v.updatedAt]); }
  async #positionHistory(v: PositionDirectoryEntry): Promise<void> { await this.db.execute("insert into organization.position_directory_history (position_id,revision,name,active,recorded_at) values ($1,$2,$3,$4,$5)", [v.positionId, v.revision, v.name, v.active, v.updatedAt]); }
}
export const createPrismaOrganizationDirectoryStore = (runtime: OrganizationDirectoryPersistenceRuntime): OrganizationDirectoryStore => new PrismaOrganizationDirectoryStore(runtime);
export const createPostgresOrganizationDirectoryStore = createPrismaOrganizationDirectoryStore;
