import { EventingError } from "./errors.js";
import type { DatabaseQueryResult, DatabaseRuntime } from "@ai-crm/database";
import type { EventingBacklog, EventingReconciliationInput, EventingReconciliationReport, JobEnvelope, JobStatus, MessageKind } from "./types.js";
import type { ClaimedOutboxRecord, EventingStore, InboxReceipt, IsolationRecord, JobRecord, OutboxRecord } from "./store.js";

export type EventingPersistenceResult<Row = Record<string, unknown>> = DatabaseQueryResult<Row>;
export type EventingPersistenceRuntime = Pick<DatabaseRuntime,"execute"|"withTransaction">;

interface OutboxRow { message_id: string; message_kind: MessageKind; message_type: string; message_version: number; producer: string; occurred_at: Date | string; available_at: Date | string; correlation_id: string; causation_id: string | null; traceparent: string | null; tracestate: string | null; payload: unknown; payload_sha256: string; attempt_count: number; status: OutboxRecord["status"]; claim_token: string | null; claimed_at: Date | string | null; published_at: Date | string | null; isolated_at: Date | string | null; last_error_code: string | null; }
interface JobRow { job_id: string; idempotency_key: string; fingerprint: string; status: JobStatus; envelope: JobEnvelope | string; cancel_reason: string | null; }
const date = (value: Date | string): Date => value instanceof Date ? value : new Date(value);
const optional = <K extends string, V>(key: K, value: V | null): Partial<Record<K, V>> => value === null ? {} : { [key]: value } as Partial<Record<K, V>>;
const mapOutbox = (row: OutboxRow): OutboxRecord => ({ messageId: row.message_id, messageKind: row.message_kind, messageType: row.message_type, messageVersion: row.message_version, producer: row.producer, occurredAt: date(row.occurred_at), availableAt: date(row.available_at), correlationId: row.correlation_id, payload: typeof row.payload === "string" ? row.payload : JSON.stringify(row.payload), payloadSha256: row.payload_sha256, attemptCount: row.attempt_count, status: row.status, ...optional("causationId", row.causation_id), ...optional("traceparent", row.traceparent), ...optional("tracestate", row.tracestate), ...optional("claimToken", row.claim_token), ...(row.claimed_at === null ? {} : { claimedAt: date(row.claimed_at) }), ...(row.published_at === null ? {} : { publishedAt: date(row.published_at) }), ...(row.isolated_at === null ? {} : { isolatedAt: date(row.isolated_at) }), ...optional("lastErrorCode", row.last_error_code) });
const mapJob = (row: JobRow): JobRecord => ({ jobId: row.job_id, idempotencyKey: row.idempotency_key, fingerprint: row.fingerprint, status: row.status, envelope: typeof row.envelope === "string" ? JSON.parse(row.envelope) as JobEnvelope : row.envelope, ...optional("cancelReason", row.cancel_reason) });
const conflict = (error: unknown): never => { if ((error as { code?: string }).code === "23505") throw new EventingError("eventing_conflict"); throw error; };

/** Prisma persistence adapter; SKIP LOCKED and Inbox serialization stay parameterized raw SQL. */
class PrismaEventingStore implements EventingStore {
  constructor(private readonly db: EventingPersistenceRuntime) {}
  transaction<T>(work: () => Promise<T>): Promise<T> { return this.db.withTransaction(work); }
  withInboxTransaction<T>(messageId:string,consumer:string,work:()=>Promise<T>):Promise<T>{return this.db.withTransaction(async()=>{await this.db.execute("select pg_advisory_xact_lock(hashtextextended($1,0))",[`${messageId}:${consumer}`]);return work();});}
  async appendOutbox(row: OutboxRecord): Promise<void> { try { await this.db.execute(`insert into platform_eventing.outbox_messages (message_id,message_kind,message_type,message_version,producer,occurred_at,available_at,correlation_id,causation_id,traceparent,tracestate,payload,payload_sha256,attempt_count,status) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12::jsonb,$13,$14,$15)`, [row.messageId,row.messageKind,row.messageType,row.messageVersion,row.producer,row.occurredAt,row.availableAt,row.correlationId,row.causationId ?? null,row.traceparent ?? null,row.tracestate ?? null,row.payload,row.payloadSha256,row.attemptCount,row.status]); } catch (error) { conflict(error); } }
  async getOutbox(id: string): Promise<OutboxRecord | undefined> { const result = await this.db.execute<OutboxRow>("select * from platform_eventing.outbox_messages where message_id=$1", [id]); return result.rows[0] ? mapOutbox(result.rows[0]) : undefined; }
  async claimOutbox(input: { readonly at: Date; readonly staleBefore: Date; readonly limit: number; readonly token: () => string }): Promise<readonly ClaimedOutboxRecord[]> { return this.db.withTransaction(async () => { const ids = await this.db.execute<{ message_id: string }>(`select message_id from platform_eventing.outbox_messages where (status='pending' and available_at <= $1) or (status='publishing' and claimed_at <= $2) order by available_at,message_id for update skip locked limit $3`, [input.at,input.staleBefore,input.limit]); const claimed: ClaimedOutboxRecord[] = []; for (const item of ids.rows) { const token = input.token(); const result = await this.db.execute<OutboxRow>(`update platform_eventing.outbox_messages set status='publishing',claim_token=$2,claimed_at=$3,attempt_count=attempt_count+1 where message_id=$1 returning *`, [item.message_id,token,input.at]); if (result.rows[0]) claimed.push(mapOutbox(result.rows[0]) as ClaimedOutboxRecord); } return claimed; }); }
  async markOutboxPublished(id: string, token: string, at: Date): Promise<boolean> { return (await this.db.execute("update platform_eventing.outbox_messages set status='published',published_at=$3,claim_token=null,claimed_at=null where message_id=$1 and status='publishing' and claim_token=$2", [id,token,at])).rowCount === 1; }
  async markOutboxFailure(input: { readonly messageId: string; readonly claimToken: string; readonly at: Date; readonly availableAt: Date; readonly errorCode: string; readonly isolate: boolean }): Promise<boolean> { return (await this.db.execute(`update platform_eventing.outbox_messages set status=$3,available_at=$4,last_error_code=$5,isolated_at=case when $3='isolated' then $6 else null end,claim_token=null,claimed_at=null where message_id=$1 and status='publishing' and claim_token=$2`, [input.messageId,input.claimToken,input.isolate ? "isolated" : "pending",input.availableAt,input.errorCode,input.at])).rowCount === 1; }
  async replayOutbox(id: string, at: Date): Promise<boolean> { return (await this.db.execute("update platform_eventing.outbox_messages set status='pending',attempt_count=0,available_at=$2,isolated_at=null,last_error_code=null where message_id=$1 and status='isolated'", [id,at])).rowCount === 1; }
  async findInboxReceipt(id: string, consumer: string): Promise<InboxReceipt | undefined> { const result = await this.db.execute<{ message_id: string; consumer: string; payload_sha256: string; completed_at: Date | string }>("select * from platform_eventing.inbox_receipts where message_id=$1 and consumer=$2", [id,consumer]); const row=result.rows[0]; return row ? { messageId: row.message_id, consumer: row.consumer, payloadSha256: row.payload_sha256, completedAt: date(row.completed_at) } : undefined; }
  async createInboxReceipt(row: InboxReceipt): Promise<void> { try { await this.db.execute("insert into platform_eventing.inbox_receipts (message_id,consumer,payload_sha256,completed_at) values ($1,$2,$3,$4)", [row.messageId,row.consumer,row.payloadSha256,row.completedAt]); } catch (error) { conflict(error); } }
  async createIsolation(row: IsolationRecord): Promise<void> { await this.db.execute("insert into platform_eventing.isolations (isolation_id,message_id,consumer,payload_sha256,reason_code,attempt_count,isolated_at) values ($1,$2,$3,$4,$5,$6,$7) on conflict (message_id,consumer,payload_sha256,reason_code) do nothing", [row.isolationId,row.messageId,row.consumer,row.payloadSha256,row.reason,row.attempt,row.isolatedAt]); }
  async findJob(id: string): Promise<JobRecord | undefined> { const result=await this.db.execute<JobRow>("select * from platform_eventing.job_requests where job_id=$1",[id]); return result.rows[0] ? mapJob(result.rows[0]) : undefined; }
  async findJobByIdempotencyKey(key: string): Promise<JobRecord | undefined> { const result=await this.db.execute<JobRow>("select * from platform_eventing.job_requests where idempotency_key=$1",[key]); return result.rows[0] ? mapJob(result.rows[0]) : undefined; }
  async createJob(row: JobRecord): Promise<void> { try { await this.db.execute("insert into platform_eventing.job_requests (job_id,idempotency_key,fingerprint,status,envelope) values ($1,$2,$3,$4,$5::jsonb)",[row.jobId,row.idempotencyKey,row.fingerprint,row.status,JSON.stringify(row.envelope)]); } catch(error){ conflict(error); } }
  async claimJob(id:string):Promise<JobRecord|undefined>{const result=await this.db.execute<JobRow>("update platform_eventing.job_requests set status='processing',updated_at=now() where job_id=$1 and status='queued' returning *",[id]);return result.rows[0]?mapJob(result.rows[0]):undefined;}
  async cancelJob(id:string,reason:string):Promise<JobRecord|undefined>{const result=await this.db.execute<JobRow>("update platform_eventing.job_requests set status='cancelled',cancel_reason=$2,updated_at=now() where job_id=$1 and status='queued' returning *",[id,reason]);return result.rows[0]?mapJob(result.rows[0]):this.findJob(id);}
  async completeJob(id:string):Promise<boolean>{return(await this.db.execute("update platform_eventing.job_requests set status='completed',updated_at=now() where job_id=$1 and status='processing'",[id])).rowCount===1;}
  async isolateJob(id:string):Promise<boolean>{return(await this.db.execute("update platform_eventing.job_requests set status='isolated',updated_at=now() where job_id=$1 and status in ('queued','processing')",[id])).rowCount===1;}
  async backlog():Promise<EventingBacklog>{const result=await this.db.execute<{pending_count:string;publishing_count:string;isolated_count:string;inbox_count:string;job_count:string;oldest:Date|string|null}>(`select count(*) filter(where status='pending')::text pending_count,count(*) filter(where status='publishing')::text publishing_count,min(available_at) filter(where status='pending') oldest,(count(*) filter(where status='isolated')+(select count(*) from platform_eventing.isolations where released_at is null))::text isolated_count,(select count(*)::text from platform_eventing.inbox_receipts) inbox_count,(select count(*)::text from platform_eventing.job_requests where status='queued') job_count from platform_eventing.outbox_messages`);const row=result.rows[0]??{pending_count:"0",publishing_count:"0",isolated_count:"0",inbox_count:"0",job_count:"0",oldest:null};return{pendingCount:Number(row.pending_count),publishingCount:Number(row.publishing_count),isolatedCount:Number(row.isolated_count),inboxReceiptCount:Number(row.inbox_count),queuedJobCount:Number(row.job_count),...(row.oldest===null?{}:{oldestPendingAt:date(row.oldest).toISOString()})};}
  async reconcile(input:EventingReconciliationInput):Promise<EventingReconciliationReport>{const missingOutboxMessageIds:string[]=[];const isolatedOutboxMessageIds:string[]=[];for(const id of input.expectedOutboxMessageIds){const row=await this.getOutbox(id);if(!row)missingOutboxMessageIds.push(id);else if(row.status==="isolated")isolatedOutboxMessageIds.push(id);}const missingInbox=[];for(const expected of input.expectedInbox)if(!await this.findInboxReceipt(expected.messageId,expected.consumer))missingInbox.push(expected);return{missingOutboxMessageIds,isolatedOutboxMessageIds,missingInbox};}
}

export const createPrismaEventingStore = (runtime: EventingPersistenceRuntime): EventingStore => new PrismaEventingStore(runtime);
/** Compatibility alias for existing application composition. */
export const createPostgresEventingStore = createPrismaEventingStore;
