import { FileCenterError } from "./errors.js";
import type { FileCenterPersistenceRuntime, FileCenterStore } from "./store.js";
import type { ContentVersion, FileLifecycleEvent, FileMetadata, ResourceLink, UploadSession } from "./types.js";

interface FileRow { classification_reference: string | null; created_at: string; display_name: string; file_id: string; owner_module: string; uploaded_by: FileMetadata["uploadedBy"] }
interface VersionRow { actual_size_bytes: number | string | null; checksum_sha256: string | null; completed_at: string | null; content_version_id: string; created_at: string; declared_media_type: string; declared_size_bytes: number | string; detected_media_type: string | null; file_id: string; object_handle: string; scanned_at: string | null; status: ContentVersion["status"]; version_number: number }
interface SessionRow { completed_at: string | null; content_version_id: string; created_at: string; expires_at: string; file_id: string; session_id: string; status: UploadSession["status"] }
interface LinkRow { content_version_id: string; file_id: string; linked_at: string; link_id: string; owner_module: string; relation_type: string; resource_id: string; resource_type: string; unlinked_at: string | null }
interface ReceiptRow { fingerprint: string; result: unknown }
const required = <T>(rows: readonly T[]): T => { const row = rows[0]; if (!row) throw new FileCenterError("file_center_operation_conflict"); return row; };
const iso = (value: string): string => new Date(value).toISOString();
const file = (row: FileRow): FileMetadata => ({ ...(row.classification_reference === null ? {} : { classificationReference: row.classification_reference }), createdAt: iso(row.created_at), displayName: row.display_name, fileId: row.file_id, ownerModule: row.owner_module, uploadedBy: structuredClone(row.uploaded_by), version: 1 });
const version = (row: VersionRow): ContentVersion => ({ ...(row.actual_size_bytes === null ? {} : { actualSizeBytes: Number(row.actual_size_bytes) }), ...(row.checksum_sha256 === null ? {} : { checksumSha256: row.checksum_sha256 }), ...(row.completed_at === null ? {} : { completedAt: iso(row.completed_at) }), contentVersionId: row.content_version_id, createdAt: iso(row.created_at), declaredMediaType: row.declared_media_type, declaredSizeBytes: Number(row.declared_size_bytes), ...(row.detected_media_type === null ? {} : { detectedMediaType: row.detected_media_type }), fileId: row.file_id, ...(row.scanned_at === null ? {} : { scannedAt: iso(row.scanned_at) }), status: row.status, version: 1, versionNumber: row.version_number });
const session = (row: SessionRow): UploadSession => ({ contentVersionId: row.content_version_id, createdAt: iso(row.created_at), expiresAt: iso(row.expires_at), fileId: row.file_id, sessionId: row.session_id, status: row.status, version: 1 });
const link = (row: LinkRow): ResourceLink => ({ contentVersionId: row.content_version_id, fileId: row.file_id, linkedAt: iso(row.linked_at), linkId: row.link_id, ownerModule: row.owner_module, relationType: row.relation_type, resource: { resourceId: row.resource_id, resourceType: row.resource_type }, ...(row.unlinked_at === null ? {} : { unlinkedAt: iso(row.unlinked_at) }), version: 1 });
const persistenceError = (error: unknown): never => { const code = String((error as { code?: unknown }).code); if (code === "23503") throw new FileCenterError("file_center_not_found", { cause: error }); if (["23505", "23514", "55000"].includes(code)) throw new FileCenterError("file_center_operation_conflict", { cause: error }); throw error; };

export function createPrismaFileCenterStore(runtime: FileCenterPersistenceRuntime): FileCenterStore {
  const transaction = <T>(work: () => Promise<T>) => runtime.withTransaction(async () => { try { return await work(); } catch (error) { return persistenceError(error); } });
  const lock = (key: string) => runtime.execute("select pg_advisory_xact_lock(hashtextextended($1,0))", [key]);
  const receipt = async (operationId: string, fingerprint: string): Promise<ReceiptRow | undefined> => { const row = (await runtime.execute<ReceiptRow>("select fingerprint,result from file_center.operation_receipts where operation_id=$1 for update", [operationId])).rows[0]; if (row && row.fingerprint !== fingerprint) throw new FileCenterError("file_center_operation_conflict"); return row; };
  const saveReceipt = (operationId: string, fingerprintValue: string, result: unknown) => runtime.execute("insert into file_center.operation_receipts(operation_id,fingerprint,result) values($1,$2,$3::jsonb)", [operationId, fingerprintValue, JSON.stringify(result)]);
  const saveEvent = (event: FileLifecycleEvent) => runtime.execute("insert into file_center.outbox_events(event_id,event_type,resource_id,occurred_at,payload) values($1,$2,$3,$4,$5::jsonb)", [event.eventId, event.eventType, event.resourceId, event.occurredAt, JSON.stringify(event)]);
  const findVersion = async (contentVersionId: string) => {
    const query = await runtime.execute<VersionRow & FileRow & { file_created_at: string }>("select v.*,f.owner_module,f.display_name,f.classification_reference,f.uploaded_by,f.created_at file_created_at from file_center.content_versions v join file_center.files f using(file_id) where v.content_version_id=$1", [contentVersionId]);
    const row = query.rows[0]; if (!row) return undefined; const metadata = file({ ...row, created_at: row.file_created_at }); return { contentVersion: version(row), file: metadata, objectHandle: row.object_handle };
  };
  return {
    findContentVersion: findVersion,
    findFile: async (fileId) => { const row = (await runtime.execute<FileRow>("select * from file_center.files where file_id=$1", [fileId])).rows[0]; return row ? file(row) : undefined; },
    findSession: async (sessionId) => { const row = (await runtime.execute<SessionRow>("select * from file_center.upload_sessions where session_id=$1", [sessionId])).rows[0]; if (!row) return undefined; const joined = await findVersion(row.content_version_id); if (!joined) throw new FileCenterError("file_center_operation_conflict"); return { ...joined, session: session(row) }; },
    findLink: async (linkId) => { const row = (await runtime.execute<LinkRow>("select * from file_center.resource_links where link_id=$1", [linkId])).rows[0]; return row ? link(row) : undefined; },
    findOperationReceipt: (operationId, fingerprintValue) => transaction(async () => (await receipt(operationId, fingerprintValue))?.result),
    findActiveLink: async (fileId, contentVersionId, target) => { const row = (await runtime.execute<LinkRow>("select * from file_center.resource_links where file_id=$1 and content_version_id=$2 and resource_type=$3 and resource_id=$4 and unlinked_at is null", [fileId, contentVersionId, target.resourceType, target.resourceId])).rows[0]; return row ? link(row) : undefined; },
    createUpload: (input) => transaction(async () => {
      await lock(`operation:${input.operationId}`); const prior = await receipt(input.operationId, input.fingerprint); if (prior) return { ...(prior.result as { contentVersion: ContentVersion; file: FileMetadata; objectHandle: string; session: UploadSession }), replayed: true };
      await runtime.execute("insert into file_center.files(file_id,owner_module,display_name,classification_reference,uploaded_by,created_at) values($1,$2,$3,$4,$5::jsonb,$6)", [input.file.fileId, input.file.ownerModule, input.file.displayName, input.file.classificationReference ?? null, JSON.stringify(input.file.uploadedBy), input.file.createdAt]);
      await runtime.execute("insert into file_center.content_versions(content_version_id,file_id,version_number,object_handle,declared_media_type,declared_size_bytes,status,created_at) values($1,$2,$3,$4,$5,$6,$7,$8)", [input.contentVersion.contentVersionId, input.contentVersion.fileId, input.contentVersion.versionNumber, input.objectHandle, input.contentVersion.declaredMediaType, input.contentVersion.declaredSizeBytes, input.contentVersion.status, input.contentVersion.createdAt]);
      await runtime.execute("insert into file_center.upload_sessions(session_id,file_id,content_version_id,status,created_at,expires_at) values($1,$2,$3,$4,$5,$6)", [input.session.sessionId, input.session.fileId, input.session.contentVersionId, input.session.status, input.session.createdAt, input.session.expiresAt]);
      const result = { contentVersion: input.contentVersion, file: input.file, objectHandle: input.objectHandle, session: input.session }; await saveReceipt(input.operationId, input.fingerprint, result); return { ...structuredClone(result), replayed: false };
    }),
    createVersionUpload: (input) => transaction(async () => {
      await lock(`operation:${input.operationId}`); const prior = await receipt(input.operationId, input.fingerprint); if (prior) return { ...(prior.result as { contentVersion: ContentVersion; file: FileMetadata; objectHandle: string; session: UploadSession }), replayed: true }; await lock(`file:${input.contentVersion.fileId}`); const metadataRow = required((await runtime.execute<FileRow>("select * from file_center.files where file_id=$1", [input.contentVersion.fileId])).rows); const versionNumber = Number(required((await runtime.execute<{ next_version: number }>("select coalesce(max(version_number),0)+1 next_version from file_center.content_versions where file_id=$1", [input.contentVersion.fileId])).rows).next_version); const contentVersion: ContentVersion = { ...input.contentVersion, versionNumber }; await runtime.execute("insert into file_center.content_versions(content_version_id,file_id,version_number,object_handle,declared_media_type,declared_size_bytes,status,created_at) values($1,$2,$3,$4,$5,$6,$7,$8)", [contentVersion.contentVersionId, contentVersion.fileId, versionNumber, input.objectHandle, contentVersion.declaredMediaType, contentVersion.declaredSizeBytes, contentVersion.status, contentVersion.createdAt]); await runtime.execute("insert into file_center.upload_sessions(session_id,file_id,content_version_id,status,created_at,expires_at) values($1,$2,$3,$4,$5,$6)", [input.session.sessionId, input.session.fileId, input.session.contentVersionId, input.session.status, input.session.createdAt, input.session.expiresAt]); const result = { contentVersion, file: file(metadataRow), objectHandle: input.objectHandle, session: input.session }; await saveReceipt(input.operationId, input.fingerprint, result); return { ...structuredClone(result), replayed: false };
    }),
    completeUpload: (input) => transaction(async () => {
      await lock(`operation:${input.operationId}`); const prior = await receipt(input.operationId, input.fingerprint); if (prior) return { ...(prior.result as { contentVersion: ContentVersion }), replayed: true }; await lock(`session:${input.sessionId}`);
      const current = required((await runtime.execute<SessionRow>("select * from file_center.upload_sessions where session_id=$1 and $2::timestamptz<expires_at for update", [input.sessionId, input.completedAt])).rows); if (current.status !== "created") throw new FileCenterError("file_center_operation_conflict");
      const changed = required((await runtime.execute<VersionRow>("update file_center.content_versions set actual_size_bytes=$2,detected_media_type=$3,checksum_sha256=$4,status='pending_scan',completed_at=$5 where content_version_id=$1 and status='awaiting_upload' returning *", [current.content_version_id, input.sizeBytes, input.detectedMediaType ?? null, input.checksumSha256 ?? null, input.completedAt])).rows); await runtime.execute("update file_center.upload_sessions set status='pending_scan',completed_at=$2 where session_id=$1", [input.sessionId, input.completedAt]);
      const result = { contentVersion: version(changed) }; await saveEvent(input.event); await saveReceipt(input.operationId, input.fingerprint, result); return { ...result, replayed: false };
    }),
    recordScan: (input) => transaction(async () => {
      await lock(`operation:${input.operationId}`); const prior = await receipt(input.operationId, input.fingerprint); if (prior) return { ...(prior.result as { contentVersion: ContentVersion; objectHandle: string }), replayed: true }; await lock(`version:${input.contentVersionId}`); const status = input.outcome === "clean" ? "available" : "quarantine_pending";
      const changed = required((await runtime.execute<VersionRow>("update file_center.content_versions set status=$2,scanned_at=$3,scanner_version=$4 where content_version_id=$1 and status='pending_scan' returning *", [input.contentVersionId, status, input.scannedAt, input.scannerVersion])).rows); const result = { contentVersion: version(changed), objectHandle: changed.object_handle }; if (input.event) await saveEvent(input.event); await saveReceipt(input.operationId, input.fingerprint, result); return { ...result, replayed: false };
    }),
    completeQuarantine: (input) => transaction(async () => {
      await lock(`version:${input.contentVersionId}`); const current = required((await runtime.execute<VersionRow>("select * from file_center.content_versions where content_version_id=$1 for update", [input.contentVersionId])).rows); if (current.status === "quarantined") return version(current); if (current.status !== "quarantine_pending") throw new FileCenterError("file_center_operation_conflict"); const changed = required((await runtime.execute<VersionRow>("update file_center.content_versions set status='quarantined' where content_version_id=$1 returning *", [input.contentVersionId])).rows); await saveEvent(input.event); return version(changed);
    }),
    linkResource: (input) => transaction(async () => {
      await lock(`operation:${input.operationId}`); const prior = await receipt(input.operationId, input.fingerprint); if (prior) return { ...(prior.result as { link: ResourceLink }), replayed: true }; const state = (await runtime.execute<{ status: string }>("select status from file_center.content_versions where content_version_id=$1 and file_id=$2", [input.link.contentVersionId, input.link.fileId])).rows[0]; if (!state) throw new FileCenterError("file_center_not_found"); if (state.status !== "available") throw new FileCenterError("file_center_not_ready");
      const inserted = required((await runtime.execute<LinkRow>("insert into file_center.resource_links(link_id,file_id,content_version_id,owner_module,resource_type,resource_id,relation_type,linked_at) values($1,$2,$3,$4,$5,$6,$7,$8) returning *", [input.link.linkId, input.link.fileId, input.link.contentVersionId, input.link.ownerModule, input.link.resource.resourceType, input.link.resource.resourceId, input.link.relationType, input.link.linkedAt])).rows); const result = { link: link(inserted) }; await saveEvent(input.event); await saveReceipt(input.operationId, input.fingerprint, result); return { ...result, replayed: false };
    }),
    unlinkResource: (input) => transaction(async () => {
      await lock(`operation:${input.operationId}`); const prior = await receipt(input.operationId, input.fingerprint); if (prior) return { ...(prior.result as { link: ResourceLink }), replayed: true }; const changed = required((await runtime.execute<LinkRow>("update file_center.resource_links set unlinked_at=$2 where link_id=$1 and unlinked_at is null returning *", [input.linkId, input.unlinkedAt])).rows); const result = { link: link(changed) }; await saveEvent(input.event); await saveReceipt(input.operationId, input.fingerprint, result); return { ...result, replayed: false };
    }),
    cleanupSession: (input) => transaction(async () => {
      await lock(`operation:${input.operationId}`); const prior = await receipt(input.operationId, input.fingerprint); if (prior) return { ...(prior.result as { objectHandle: string; session: UploadSession }), replayed: true };
      const current = required((await runtime.execute<SessionRow & { object_handle: string }>("select s.*,v.object_handle from file_center.upload_sessions s join file_center.content_versions v using(content_version_id) where session_id=$1 for update of s,v", [input.sessionId])).rows); if (!["created", "expired", "cleanup_pending"].includes(current.status)) throw new FileCenterError("file_center_operation_conflict");
      await runtime.execute("update file_center.upload_sessions set status='cleanup_pending' where session_id=$1", [input.sessionId]); await runtime.execute("update file_center.content_versions set status='cleanup_pending' where content_version_id=$1 and status in('awaiting_upload','cleanup_pending')", [current.content_version_id]); const result = { objectHandle: current.object_handle, session: session({ ...current, status: "cleanup_pending" }) }; await saveReceipt(input.operationId, input.fingerprint, result); return { ...result, replayed: false };
    }),
    completeCleanup: (sessionId) => transaction(async () => {
      const current = required((await runtime.execute<SessionRow>("select * from file_center.upload_sessions where session_id=$1 for update", [sessionId])).rows); if (current.status === "cleaned") return session(current); if (current.status !== "cleanup_pending") throw new FileCenterError("file_center_operation_conflict"); required((await runtime.execute<{ content_version_id: string }>("update file_center.content_versions set status='deleted' where content_version_id=$1 and status='cleanup_pending' returning content_version_id", [current.content_version_id])).rows); const changed = required((await runtime.execute<SessionRow>("update file_center.upload_sessions set status='cleaned' where session_id=$1 returning *", [sessionId])).rows); return session(changed);
    }),
    markReconciled: (input) => transaction(async () => {
      await lock(`operation:${input.operationId}`); const prior = await receipt(input.operationId, input.fingerprint); if (prior) return { ...(prior.result as { contentVersion: ContentVersion }), replayed: true }; await lock(`version:${input.contentVersionId}`);
      let changed: VersionRow; if (input.objectExists) changed = required((await runtime.execute<VersionRow>("select * from file_center.content_versions where content_version_id=$1", [input.contentVersionId])).rows); else { const current = required((await runtime.execute<VersionRow>("select * from file_center.content_versions where content_version_id=$1 for update", [input.contentVersionId])).rows); if (current.status !== "pending_scan" && current.status !== "available") changed = current; else changed = required((await runtime.execute<VersionRow>("update file_center.content_versions set status='object_missing' where content_version_id=$1 returning *", [input.contentVersionId])).rows); }
      const result = { contentVersion: version(changed) }; await saveReceipt(input.operationId, input.fingerprint, result); return { ...result, replayed: false };
    }),
  };
}

/** @deprecated Use createPrismaFileCenterStore. */
export const createPostgresFileCenterStore = createPrismaFileCenterStore;
