import { sql } from "drizzle-orm";
import { bigint, check, index, integer, jsonb, pgSchema, text, timestamp, uniqueIndex, uuid, varchar } from "drizzle-orm/pg-core";

const files = pgSchema("file_center");
export const fileMetadata = files.table("files", { fileId: uuid("file_id").primaryKey(), ownerModule: varchar("owner_module", { length: 128 }).notNull(), displayName: varchar("display_name", { length: 255 }).notNull(), classificationReference: varchar("classification_reference", { length: 128 }), uploadedBy: jsonb("uploaded_by").notNull(), createdAt: timestamp("created_at", { mode: "string", withTimezone: true }).notNull() });
export const contentVersions = files.table("content_versions", { contentVersionId: uuid("content_version_id").primaryKey(), fileId: uuid("file_id").notNull(), versionNumber: integer("version_number").notNull(), objectHandle: varchar("object_handle", { length: 255 }).notNull(), declaredMediaType: varchar("declared_media_type", { length: 255 }).notNull(), declaredSizeBytes: bigint("declared_size_bytes", { mode: "number" }).notNull(), actualSizeBytes: bigint("actual_size_bytes", { mode: "number" }), detectedMediaType: varchar("detected_media_type", { length: 255 }), checksumSha256: varchar("checksum_sha256", { length: 64 }), status: varchar("status", { length: 32 }).notNull(), createdAt: timestamp("created_at", { mode: "string", withTimezone: true }).notNull(), completedAt: timestamp("completed_at", { mode: "string", withTimezone: true }), scannedAt: timestamp("scanned_at", { mode: "string", withTimezone: true }), scannerVersion: varchar("scanner_version", { length: 128 }) }, (table) => [uniqueIndex("file_center_content_handle_unique").on(table.objectHandle), uniqueIndex("file_center_content_version_unique").on(table.fileId, table.versionNumber), check("file_center_content_version_positive", sql`${table.versionNumber}>0`)]);
export const uploadSessions = files.table("upload_sessions", { sessionId: uuid("session_id").primaryKey(), fileId: uuid("file_id").notNull(), contentVersionId: uuid("content_version_id").notNull(), status: varchar("status", { length: 32 }).notNull(), createdAt: timestamp("created_at", { mode: "string", withTimezone: true }).notNull(), expiresAt: timestamp("expires_at", { mode: "string", withTimezone: true }).notNull(), completedAt: timestamp("completed_at", { mode: "string", withTimezone: true }) }, (table) => [index("file_center_upload_expiry_index").on(table.status, table.expiresAt), check("file_center_upload_interval", sql`${table.createdAt}<${table.expiresAt}`)]);
export const resourceLinks = files.table("resource_links", { linkId: uuid("link_id").primaryKey(), fileId: uuid("file_id").notNull(), contentVersionId: uuid("content_version_id").notNull(), ownerModule: varchar("owner_module", { length: 128 }).notNull(), resourceType: varchar("resource_type", { length: 128 }).notNull(), resourceId: varchar("resource_id", { length: 255 }).notNull(), relationType: varchar("relation_type", { length: 128 }).notNull(), linkedAt: timestamp("linked_at", { mode: "string", withTimezone: true }).notNull(), unlinkedAt: timestamp("unlinked_at", { mode: "string", withTimezone: true }) });
export const operationReceipts = files.table("operation_receipts", { operationId: uuid("operation_id").primaryKey(), fingerprint: varchar("fingerprint", { length: 64 }).notNull(), result: jsonb("result").notNull() });
export const outboxEvents = files.table("outbox_events", { eventId: uuid("event_id").primaryKey(), eventType: varchar("event_type", { length: 80 }).notNull(), resourceId: uuid("resource_id").notNull(), occurredAt: timestamp("occurred_at", { mode: "string", withTimezone: true }).notNull(), payload: jsonb("payload").notNull(), publishedAt: timestamp("published_at", { mode: "string", withTimezone: true }), lastError: text("last_error") });
