import { createHash } from "node:crypto";

import { WorkforceAccessError } from "./errors.js";
import type { WorkforceAccessMutation, WorkforceAccessStore } from "./store.js";
import type { CreateWorkforceAccountCommand, LoginIdentifierHistory, ReleasePhoneCommand, SetAccountStatusCommand, UpdateLoginIdentifiersCommand, WorkforceAccessAuthorizer, WorkforceAccessCommandMetadata, WorkforceAccessServiceApi, WorkforceAccount, WorkforceAccountPage, WorkforceAccountStatus } from "./types.js";
import { normalizePhone, normalizeUsername, requireId, requireText, requireTimestamp } from "./validation.js";

export class WorkforceAccessService implements WorkforceAccessServiceApi {
  constructor(private readonly store: WorkforceAccessStore, private readonly authorizer: WorkforceAccessAuthorizer) {}
  async createAccount(command: CreateWorkforceAccountCommand): Promise<WorkforceAccount> {
    this.#metadata(command); requireId(command.accountId); requireId(command.workforcePersonId); requireTimestamp(command.createdAt);
    const usernameNormalized = normalizeUsername(command.username); const phone = command.phone === undefined ? undefined : normalizePhone(command.phone); await this.#authorize(command, "account_create");
    const account: WorkforceAccount = { accountId: command.accountId, createdAt: command.createdAt, ...(phone === undefined ? {} : { phone }), revision: 0, securityRevision: 0, status: command.status ?? "active", updatedAt: command.createdAt, username: command.username, usernameNormalized, workforcePersonId: command.workforcePersonId };
    const identifiers = [this.#identifier(account.accountId, "username", command.username, usernameNormalized, command.operationId), ...(phone === undefined ? [] : [this.#identifier(account.accountId, "phone", phone, phone, command.operationId)])]; await this.#commit(command, account, { account, identifiers, kind: "create" }); return this.getAccount(command.accountId);
  }
  async getAccount(accountId: string): Promise<WorkforceAccount> { requireId(accountId); const account = await this.store.findAccount(accountId); if (account === undefined) throw new WorkforceAccessError("entity_not_found"); return account; }
  listAccounts(input: Readonly<{ cursor?: string; limit?: number; status?: WorkforceAccountStatus }>): Promise<WorkforceAccountPage> { const limit = input.limit ?? 50; if (!Number.isSafeInteger(limit) || limit < 1 || limit > 200) throw new WorkforceAccessError("input_invalid"); if (input.cursor !== undefined) requireId(input.cursor); return this.store.listAccounts({ ...input, limit }); }
  async listIdentifierHistory(accountId: string): Promise<readonly LoginIdentifierHistory[]> { await this.getAccount(accountId); return this.store.listIdentifierHistory(accountId); }
  async updateLoginIdentifiers(command: UpdateLoginIdentifiersCommand): Promise<WorkforceAccount> {
    this.#metadata(command); requireId(command.accountId); requireTimestamp(command.updatedAt); this.#revision(command.expectedRevision); if (command.username === undefined && command.phone === undefined) throw new WorkforceAccessError("input_invalid");
    const current = await this.getAccount(command.accountId); const usernameNormalized = command.username === undefined ? undefined : normalizeUsername(command.username); const phone = command.phone === undefined || command.phone === null ? command.phone : normalizePhone(command.phone); await this.#authorize(command, "account_identity_update"); const identifiers: LoginIdentifierHistory[] = [];
    if (command.username !== undefined) { const normalized = normalizeUsername(command.username); if (normalized !== current.usernameNormalized) identifiers.push(this.#identifier(command.accountId, "username", command.username, normalized, command.operationId)); } if (phone !== undefined && phone !== null && phone !== current.phone) identifiers.push(this.#identifier(command.accountId, "phone", phone, phone, command.operationId));
    await this.#commit(command, current, { accountId: command.accountId, expectedRevision: command.expectedRevision, identifiers, kind: "update_identifiers", ...(command.username === undefined ? {} : { username: command.username, usernameNormalized }), ...(phone === undefined ? {} : { phone }), updatedAt: command.updatedAt }); return this.getAccount(command.accountId);
  }
  async setStatus(command: SetAccountStatusCommand): Promise<WorkforceAccount> { this.#metadata(command); requireId(command.accountId); requireTimestamp(command.updatedAt); this.#revision(command.expectedRevision); const current = await this.getAccount(command.accountId); await this.#authorize(command, "account_status_update"); await this.#commit(command, current, { accountId: command.accountId, expectedRevision: command.expectedRevision, kind: "set_status", status: command.status, updatedAt: command.updatedAt }); return this.getAccount(command.accountId); }
  async releasePhone(command: ReleasePhoneCommand): Promise<void> { this.#metadata(command); requireId(command.accountId); requireTimestamp(command.releasedAt); this.#revision(command.expectedRevision); const current = await this.getAccount(command.accountId); await this.#authorize(command, "account_phone_release"); await this.#commit(command, current, { accountId: command.accountId, expectedRevision: command.expectedRevision, kind: "release_phone", normalizedPhone: normalizePhone(command.phone), releasedAt: command.releasedAt }); }
  async #authorize(command: WorkforceAccessCommandMetadata & { readonly accountId: string }, action: Parameters<WorkforceAccessAuthorizer["authorize"]>[0]["action"]): Promise<void> { await this.authorizer.authorize({ accountId: command.accountId, action, actor: command.actor, operationId: command.operationId }); }
  async #commit(command: WorkforceAccessCommandMetadata, account: WorkforceAccount, mutation: WorkforceAccessMutation): Promise<void> { const request = Object.fromEntries(Object.entries(command).filter(([key]) => key !== "operationId" && key !== "traceId")); const fingerprint = createHash("sha256").update(JSON.stringify(request)).digest("hex"); await this.store.commit({ fingerprint, mutation, operation: { accountId: account.accountId, fingerprint, operationId: command.operationId, recordedAt: "updatedAt" in mutation ? mutation.updatedAt : "releasedAt" in mutation ? mutation.releasedAt : account.createdAt, status: "succeeded", traceId: command.traceId } }); }
  #identifier(accountId: string, kind: "phone" | "username", value: string, normalizedValue: string, operationId: string): LoginIdentifierHistory { const hex = createHash("sha256").update(`${operationId}:${kind}:${normalizedValue}`).digest("hex"); return { accountId, identifierId: `${hex.slice(0, 8)}-${hex.slice(8, 12)}-4${hex.slice(13, 16)}-8${hex.slice(17, 20)}-${hex.slice(20, 32)}`, kind, normalizedValue, value }; }
  #metadata(command: WorkforceAccessCommandMetadata): void { requireId(command.operationId); requireText(command.actor.actorId); requireText(command.reason, 500); requireText(command.traceId, 128); }
  #revision(value: number): void { if (!Number.isSafeInteger(value) || value < 0) throw new WorkforceAccessError("input_invalid"); }
}
