export type WorkforceAccountStatus = "active" | "disabled";
export type LoginIdentifierKind = "phone" | "username";
export interface WorkforceAccessActor { readonly actorId: string; readonly actorType: "authenticated_subject" | "system" }
export interface WorkforceAccessCommandMetadata { readonly actor: WorkforceAccessActor; readonly operationId: string; readonly reason: string; readonly traceId: string }
export interface WorkforceAccount { readonly accountId: string; readonly createdAt: string; readonly phone?: string | undefined; readonly revision: number; readonly securityRevision: number; readonly status: WorkforceAccountStatus; readonly updatedAt: string; readonly username: string; readonly usernameNormalized: string; readonly workforcePersonId: string }
export interface LoginIdentifierHistory { readonly accountId: string; readonly identifierId: string; readonly kind: LoginIdentifierKind; readonly normalizedValue: string; readonly releasedAt?: string; readonly value: string }
export interface WorkforceAccessOperation { readonly accountId: string; readonly fingerprint: string; readonly operationId: string; readonly recordedAt: string; readonly status: "succeeded"; readonly traceId: string }
export interface CreateWorkforceAccountCommand extends WorkforceAccessCommandMetadata { readonly accountId: string; readonly createdAt: string; readonly phone?: string; readonly status?: WorkforceAccountStatus; readonly username: string; readonly workforcePersonId: string }
export interface UpdateLoginIdentifiersCommand extends WorkforceAccessCommandMetadata { readonly accountId: string; readonly expectedRevision: number; readonly phone?: string | null; readonly updatedAt: string; readonly username?: string }
export interface SetAccountStatusCommand extends WorkforceAccessCommandMetadata { readonly accountId: string; readonly expectedRevision: number; readonly status: WorkforceAccountStatus; readonly updatedAt: string }
export interface ReleasePhoneCommand extends WorkforceAccessCommandMetadata { readonly accountId: string; readonly expectedRevision: number; readonly phone: string; readonly releasedAt: string }
export interface WorkforceAccountPage { readonly items: readonly WorkforceAccount[]; readonly nextCursor?: string | undefined }
export interface WorkforceAccessAuthorizer { authorize(input: Readonly<{ accountId: string; action: "account_create" | "account_identity_update" | "account_phone_release" | "account_status_update"; actor: WorkforceAccessActor; operationId: string }>): Promise<void> }
export interface WorkforceAccessServiceApi { createAccount(command: CreateWorkforceAccountCommand): Promise<WorkforceAccount>; getAccount(accountId: string): Promise<WorkforceAccount>; listAccounts(input: Readonly<{ cursor?: string; limit?: number; status?: WorkforceAccountStatus }>): Promise<WorkforceAccountPage>; listIdentifierHistory(accountId: string): Promise<readonly LoginIdentifierHistory[]>; releasePhone(command: ReleasePhoneCommand): Promise<void>; setStatus(command: SetAccountStatusCommand): Promise<WorkforceAccount>; updateLoginIdentifiers(command: UpdateLoginIdentifiersCommand): Promise<WorkforceAccount> }
