import { NotificationError } from "./errors.js";
import type { InAppNotification,NotificationPage,NotificationStore,StoredIntent,TemplateRelease } from "./types.js";
const clone=<T>(value:T):T=>structuredClone(value);
const intentKey=(producer:string,key:string):string=>`${producer}\u0000${key}`;
export class InMemoryNotificationStore implements NotificationStore {
  private readonly templates=new Map<string,TemplateRelease>();private readonly intents=new Map<string,StoredIntent>();private readonly notifications=new Map<string,InAppNotification>();
  public publishTemplate(release:TemplateRelease):Promise<"published"|"duplicate">{const key=`${release.templateKey}\u0000${String(release.version)}`;const existing=this.templates.get(key);if(existing){if(existing.contentDigest!==release.contentDigest)throw new NotificationError("NOTIFICATION_CONFLICT");return Promise.resolve("duplicate");}this.templates.set(key,clone(release));return Promise.resolve("published");}
  public getTemplate(key:string,version:number):Promise<TemplateRelease|undefined>{return Promise.resolve(clone(this.templates.get(`${key}\u0000${String(version)}`)));}
  public findIntent(producer:string,key:string):Promise<StoredIntent|undefined>{return Promise.resolve(clone(this.intents.get(intentKey(producer,key))));}
  public acceptIntent(input:{intent:StoredIntent;notifications:readonly InAppNotification[]}):Promise<{status:"created"|"duplicate";result:StoredIntent["result"]}>{const key=intentKey(input.intent.producer,input.intent.idempotencyKey);const existing=this.intents.get(key);if(existing){if(existing.fingerprint!==input.intent.fingerprint)throw new NotificationError("NOTIFICATION_CONFLICT");return Promise.resolve({status:"duplicate",result:clone(existing.result)});}const snapshot=clone(this.notifications);try{for(const item of input.notifications){if(this.notifications.has(item.notificationId))throw new NotificationError("NOTIFICATION_CONFLICT");this.notifications.set(item.notificationId,clone(item));}this.intents.set(key,clone(input.intent));return Promise.resolve({status:"created",result:clone(input.intent.result)});}catch(error){this.notifications.clear();snapshot.forEach((value,id)=>this.notifications.set(id,value));throw error;}}
  public get(principalId:string,notificationId:string):Promise<InAppNotification|undefined>{const item=this.notifications.get(notificationId);return Promise.resolve(item?.principalId===principalId&&item.preferenceDecision==="deliver"?clone(item):undefined);}
  public list(input:{principalId:string;limit:number;cursor?:string;includeArchived:boolean}):Promise<NotificationPage>{const rows=[...this.notifications.values()].filter(item=>item.principalId===input.principalId&&item.preferenceDecision==="deliver"&&(input.includeArchived||item.archivedAt===undefined)).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)||b.notificationId.localeCompare(a.notificationId)).filter(item=>input.cursor===undefined||`${item.createdAt}\u0000${item.notificationId}`<input.cursor);const items=rows.slice(0,input.limit).map(clone);const last=items.at(-1);return Promise.resolve({items,...(rows.length>input.limit&&last?{nextCursor:`${last.createdAt}\u0000${last.notificationId}`}:{})});}
  public unreadCount(principalId:string):Promise<number>{return Promise.resolve([...this.notifications.values()].filter(item=>item.principalId===principalId&&item.preferenceDecision==="deliver"&&item.readAt===undefined&&item.archivedAt===undefined).length);}
  public markRead(principalId:string,id:string,at:string):Promise<InAppNotification|undefined>{const item=this.notifications.get(id);if(!item||item.principalId!==principalId||item.preferenceDecision!=="deliver")return Promise.resolve(undefined);const next=item.readAt===undefined?{...item,readAt:at}:item;this.notifications.set(id,next);return Promise.resolve(clone(next));}
  public archive(principalId:string,id:string,at:string):Promise<InAppNotification|undefined>{const item=this.notifications.get(id);if(!item||item.principalId!==principalId||item.preferenceDecision!=="deliver")return Promise.resolve(undefined);const next=item.archivedAt===undefined?{...item,archivedAt:at}:item;this.notifications.set(id,next);return Promise.resolve(clone(next));}
}
