import type { DatabaseRuntime } from "@ai-crm/database";
import { NotificationError } from "./errors.js";
import type { InAppNotification,NotificationPage,NotificationStore,StoredIntent,TemplateRelease } from "./types.js";
export type NotificationPersistenceRuntime=Pick<DatabaseRuntime,"execute"|"withTransaction">;
interface TemplateRow {template_key:string;version:number;owner_reference:string;notification_type:string;variable_schema:Record<string,unknown>|string;title_template:string;body_template:string;content_digest:string;published_at:Date|string}
interface IntentRow {intent_id:string;producer:string;idempotency_key:string;fingerprint:string;result_json:StoredIntent["result"]|string;created_at:Date|string}
interface NotificationRow {notification_id:string;intent_id:string;principal_id:string;recipient_reference:string;resolution_reference:string;resolution_version:string;template_key:string;template_version:number;notification_type:string;title:string;body:string;source_type:string;source_id:string;deep_link:InAppNotification["deepLink"]|string;preference_decision:InAppNotification["preferenceDecision"];preference_reason:string;preference_version:string;created_at:Date|string;read_at:Date|string|null;archived_at:Date|string|null}
const iso=(value:Date|string):string=>value instanceof Date?value.toISOString():new Date(value).toISOString();const json=<T>(value:T|string):T=>typeof value==="string"?JSON.parse(value) as T:value;
const template=(row:TemplateRow):TemplateRelease=>({templateKey:row.template_key,version:row.version,ownerReference:row.owner_reference,notificationType:row.notification_type,variableSchema:json(row.variable_schema),titleTemplate:row.title_template,bodyTemplate:row.body_template,contentDigest:row.content_digest,publishedAt:iso(row.published_at)});
const notification=(row:NotificationRow):InAppNotification=>({notificationId:row.notification_id,intentId:row.intent_id,principalId:row.principal_id,recipientReference:row.recipient_reference,resolutionReference:row.resolution_reference,resolutionVersion:row.resolution_version,templateKey:row.template_key,templateVersion:row.template_version,notificationType:row.notification_type,title:row.title,body:row.body,sourceType:row.source_type,sourceId:row.source_id,deepLink:json(row.deep_link),preferenceDecision:row.preference_decision,preferenceReason:row.preference_reason,preferenceVersion:row.preference_version,createdAt:iso(row.created_at),...(row.read_at===null?{}:{readAt:iso(row.read_at)}),...(row.archived_at===null?{}:{archivedAt:iso(row.archived_at)})});
const stored=(row:IntentRow):StoredIntent=>({intentId:row.intent_id,producer:row.producer,idempotencyKey:row.idempotency_key,fingerprint:row.fingerprint,result:json(row.result_json),createdAt:iso(row.created_at)});
/** Prisma persistence adapter. Its narrow runtime is supplied by packages/database. */
class PrismaNotificationStore implements NotificationStore{
  public constructor(private readonly db:NotificationPersistenceRuntime){}
  public async publishTemplate(release:TemplateRelease):Promise<"published"|"duplicate">{const result=await this.db.execute<TemplateRow>(`insert into platform_notifications.template_releases (template_key,version,owner_reference,notification_type,variable_schema,title_template,body_template,content_digest,published_at) values ($1,$2,$3,$4,$5::jsonb,$6,$7,$8,$9) on conflict (template_key,version) do nothing returning *`,[release.templateKey,release.version,release.ownerReference,release.notificationType,JSON.stringify(release.variableSchema),release.titleTemplate,release.bodyTemplate,release.contentDigest,release.publishedAt]);if(result.rows[0])return"published";const existing=await this.getTemplate(release.templateKey,release.version);if(!existing)throw new NotificationError("NOTIFICATION_STORAGE_UNAVAILABLE",{retryable:true});if(existing.contentDigest!==release.contentDigest)throw new NotificationError("NOTIFICATION_CONFLICT");return"duplicate";}
  public async getTemplate(key:string,version:number):Promise<TemplateRelease|undefined>{const result=await this.db.execute<TemplateRow>("select * from platform_notifications.template_releases where template_key=$1 and version=$2",[key,version]);return result.rows[0]?template(result.rows[0]):undefined;}
  public async findIntent(producer:string,key:string):Promise<StoredIntent|undefined>{const result=await this.db.execute<IntentRow>("select * from platform_notifications.notification_intents where producer=$1 and idempotency_key=$2",[producer,key]);return result.rows[0]?stored(result.rows[0]):undefined;}
  public acceptIntent(input:{intent:StoredIntent;notifications:readonly InAppNotification[]}):Promise<{status:"created"|"duplicate";result:StoredIntent["result"]}>{return this.db.withTransaction(async()=>{await this.db.execute("select pg_advisory_xact_lock(hashtextextended($1,0))",[`${input.intent.producer}:${input.intent.idempotencyKey}`]);const existing=await this.findIntent(input.intent.producer,input.intent.idempotencyKey);if(existing){if(existing.fingerprint!==input.intent.fingerprint)throw new NotificationError("NOTIFICATION_CONFLICT");return{status:"duplicate",result:existing.result};}await this.db.execute("insert into platform_notifications.notification_intents (intent_id,producer,idempotency_key,fingerprint,result_json,created_at) values ($1,$2,$3,$4,$5::jsonb,$6)",[input.intent.intentId,input.intent.producer,input.intent.idempotencyKey,input.intent.fingerprint,JSON.stringify(input.intent.result),input.intent.createdAt]);for(const item of input.notifications)await this.db.execute(`insert into platform_notifications.in_app_notifications (notification_id,intent_id,principal_id,recipient_reference,resolution_reference,resolution_version,template_key,template_version,notification_type,title,body,source_type,source_id,deep_link,preference_decision,preference_reason,preference_version,created_at) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14::jsonb,$15,$16,$17,$18)`,[item.notificationId,item.intentId,item.principalId,item.recipientReference,item.resolutionReference,item.resolutionVersion,item.templateKey,item.templateVersion,item.notificationType,item.title,item.body,item.sourceType,item.sourceId,JSON.stringify(item.deepLink),item.preferenceDecision,item.preferenceReason,item.preferenceVersion,item.createdAt]);return{status:"created",result:input.intent.result};});}
  public async get(principalId:string,id:string):Promise<InAppNotification|undefined>{const result=await this.db.execute<NotificationRow>("select * from platform_notifications.in_app_notifications where principal_id=$1 and notification_id=$2 and preference_decision='deliver'",[principalId,id]);return result.rows[0]?notification(result.rows[0]):undefined;}
  public async list(input:{principalId:string;limit:number;cursor?:string;includeArchived:boolean}):Promise<NotificationPage>{let cursorAt:string|null=null;let cursorId:string|null=null;if(input.cursor!==undefined){const split=input.cursor.split("\u0000");const at=split[0];const notificationId=split[1];if(split.length!==2||at===undefined||notificationId===undefined)throw new NotificationError("NOTIFICATION_INPUT_INVALID");cursorAt=at;cursorId=notificationId;}const result=await this.db.execute<NotificationRow>(`select * from platform_notifications.in_app_notifications where principal_id=$1 and preference_decision='deliver' and ($2::boolean or archived_at is null) and ($3::timestamptz is null or (created_at,notification_id)<($3::timestamptz,$4::uuid)) order by created_at desc,notification_id desc limit $5`,[input.principalId,input.includeArchived,cursorAt,cursorId,input.limit+1]);const items=result.rows.slice(0,input.limit).map(notification);const last=items.at(-1);return{items,...(result.rows.length>input.limit&&last?{nextCursor:`${last.createdAt}\u0000${last.notificationId}`}:{})};}
  public async unreadCount(principalId:string):Promise<number>{const result=await this.db.execute<{count:string}>("select count(*)::text count from platform_notifications.in_app_notifications where principal_id=$1 and preference_decision='deliver' and read_at is null and archived_at is null",[principalId]);return Number(result.rows[0]?.count??0);}
  public async markRead(principalId:string,id:string,at:string):Promise<InAppNotification|undefined>{const result=await this.db.execute<NotificationRow>("update platform_notifications.in_app_notifications set read_at=coalesce(read_at,$3) where principal_id=$1 and notification_id=$2 and preference_decision='deliver' returning *",[principalId,id,at]);return result.rows[0]?notification(result.rows[0]):undefined;}
  public async archive(principalId:string,id:string,at:string):Promise<InAppNotification|undefined>{const result=await this.db.execute<NotificationRow>("update platform_notifications.in_app_notifications set archived_at=coalesce(archived_at,$3) where principal_id=$1 and notification_id=$2 and preference_decision='deliver' returning *",[principalId,id,at]);return result.rows[0]?notification(result.rows[0]):undefined;}
}
export const createPrismaNotificationStore=(runtime:NotificationPersistenceRuntime):NotificationStore=>new PrismaNotificationStore(runtime);
/** @deprecated Use createPrismaNotificationStore. */
export const createPostgresNotificationStore=createPrismaNotificationStore;
