// @generated by scripts/contracts/generate.mjs. Do not edit.
export const packageId = "@ai-crm/api-client" as const;
export const internalOperations = [
  {
    "id": "getInternalApplicationRegistry",
    "method": "GET",
    "path": "/application-registry"
  },
  {
    "id": "resolveInternalApplicationDeepLink",
    "method": "POST",
    "path": "/application-registry/deep-links/resolve"
  },
  {
    "id": "beginPcLogin",
    "method": "GET",
    "path": "/auth/pc/login"
  },
  {
    "id": "completePcLogin",
    "method": "GET",
    "path": "/auth/pc/callback"
  },
  {
    "id": "getPcSession",
    "method": "GET",
    "path": "/auth/pc/session"
  },
  {
    "id": "refreshPcSession",
    "method": "POST",
    "path": "/auth/pc/refresh"
  },
  {
    "id": "logoutPcSession",
    "method": "POST",
    "path": "/auth/pc/logout"
  },
  {
    "id": "createFileUploadSession",
    "method": "POST",
    "path": "/files/upload-sessions"
  },
  {
    "id": "confirmFileUpload",
    "method": "POST",
    "path": "/files/upload-sessions/{sessionId}/confirm"
  },
  {
    "id": "createFileDownloadGrant",
    "method": "POST",
    "path": "/files/download-grants"
  },
  {
    "id": "getFormRelease",
    "method": "GET",
    "path": "/form-definitions/{definitionId}/releases/{releaseVersion}"
  },
  {
    "id": "validateFormSubmission",
    "method": "POST",
    "path": "/form-definitions/{definitionId}/releases/{releaseVersion}/validate"
  },
  {
    "id": "listNotifications",
    "method": "GET",
    "path": "/notifications"
  },
  {
    "id": "getNotificationUnreadCount",
    "method": "GET",
    "path": "/notifications/unread-count"
  },
  {
    "id": "getNotification",
    "method": "GET",
    "path": "/notifications/{notificationId}"
  },
  {
    "id": "markNotificationRead",
    "method": "POST",
    "path": "/notifications/{notificationId}/read"
  },
  {
    "id": "archiveNotification",
    "method": "POST",
    "path": "/notifications/{notificationId}/archive"
  },
  {
    "id": "getLiveness",
    "method": "GET",
    "path": "/health/live"
  },
  {
    "id": "getReadiness",
    "method": "GET",
    "path": "/health/ready"
  },
  {
    "id": "listTasks",
    "method": "GET",
    "path": "/tasks"
  },
  {
    "id": "getTask",
    "method": "GET",
    "path": "/tasks/{sourceType}/{sourceTaskId}"
  },
  {
    "id": "completeTask",
    "method": "POST",
    "path": "/tasks/{sourceType}/{sourceTaskId}/complete"
  },
  {
    "id": "reconcileTask",
    "method": "POST",
    "path": "/tasks/{sourceType}/{sourceTaskId}/reconcile"
  }
] as const;
