// @generated by scripts/contracts/generate.mjs. Do not edit.
export const packageId = "@ai-crm/api-client" as const;
export const internalOperations = [
  {
    "id": "loginPc",
    "method": "POST",
    "path": "/auth/pc/login"
  },
  {
    "id": "getPcSession",
    "method": "GET",
    "path": "/auth/pc/session"
  },
  {
    "id": "reauthenticatePc",
    "method": "POST",
    "path": "/auth/pc/reauthentication"
  },
  {
    "id": "selectPcAssignment",
    "method": "POST",
    "path": "/auth/pc/assignment"
  },
  {
    "id": "logoutPc",
    "method": "POST",
    "path": "/auth/pc/logout"
  },
  {
    "id": "loginInternalH5",
    "method": "POST",
    "path": "/auth/internal-h5/login"
  },
  {
    "id": "getInternalH5Session",
    "method": "GET",
    "path": "/auth/internal-h5/session"
  },
  {
    "id": "reauthenticateInternalH5",
    "method": "POST",
    "path": "/auth/internal-h5/reauthentication"
  },
  {
    "id": "selectInternalH5Assignment",
    "method": "POST",
    "path": "/auth/internal-h5/assignment"
  },
  {
    "id": "logoutInternalH5",
    "method": "POST",
    "path": "/auth/internal-h5/logout"
  },
  {
    "id": "loginPartTime",
    "method": "POST",
    "path": "/auth/part-time/login"
  },
  {
    "id": "getPartTimeSession",
    "method": "GET",
    "path": "/auth/part-time/session"
  },
  {
    "id": "reauthenticatePartTime",
    "method": "POST",
    "path": "/auth/part-time/reauthentication"
  },
  {
    "id": "logoutPartTime",
    "method": "POST",
    "path": "/auth/part-time/logout"
  },
  {
    "id": "createFileUploadSession",
    "method": "POST",
    "path": "/files/upload-sessions"
  },
  {
    "id": "confirmFileUpload",
    "method": "POST",
    "path": "/files/upload-sessions/{sessionId}/confirm"
  },
  {
    "id": "createFileDownloadGrant",
    "method": "POST",
    "path": "/files/download-grants"
  },
  {
    "id": "getFormRelease",
    "method": "GET",
    "path": "/form-definitions/{definitionId}/releases/{releaseVersion}"
  },
  {
    "id": "validateFormSubmission",
    "method": "POST",
    "path": "/form-definitions/{definitionId}/releases/{releaseVersion}/validate"
  },
  {
    "id": "listNotifications",
    "method": "GET",
    "path": "/notifications"
  },
  {
    "id": "getNotificationUnreadCount",
    "method": "GET",
    "path": "/notifications/unread-count"
  },
  {
    "id": "getNotification",
    "method": "GET",
    "path": "/notifications/{notificationId}"
  },
  {
    "id": "markNotificationRead",
    "method": "POST",
    "path": "/notifications/{notificationId}/read"
  },
  {
    "id": "archiveNotification",
    "method": "POST",
    "path": "/notifications/{notificationId}/archive"
  },
  {
    "id": "listNotificationTemplates",
    "method": "GET",
    "path": "/notification-templates"
  },
  {
    "id": "getNotificationTemplateAdministration",
    "method": "GET",
    "path": "/notification-templates/{templateKey}"
  },
  {
    "id": "saveNotificationTemplateDraft",
    "method": "PUT",
    "path": "/notification-templates/{templateKey}/draft"
  },
  {
    "id": "previewNotificationTemplate",
    "method": "POST",
    "path": "/notification-templates/{templateKey}/preview"
  },
  {
    "id": "publishNotificationTemplate",
    "method": "POST",
    "path": "/notification-templates/{templateKey}/publish"
  },
  {
    "id": "activateNotificationTemplateRelease",
    "method": "POST",
    "path": "/notification-templates/{templateKey}/activate"
  },
  {
    "id": "getLiveness",
    "method": "GET",
    "path": "/health/live"
  },
  {
    "id": "getReadiness",
    "method": "GET",
    "path": "/health/ready"
  },
  {
    "id": "listTasks",
    "method": "GET",
    "path": "/tasks"
  },
  {
    "id": "getTask",
    "method": "GET",
    "path": "/tasks/{sourceType}/{sourceTaskId}"
  },
  {
    "id": "completeTask",
    "method": "POST",
    "path": "/tasks/{sourceType}/{sourceTaskId}/complete"
  },
  {
    "id": "reconcileTask",
    "method": "POST",
    "path": "/tasks/{sourceType}/{sourceTaskId}/reconcile"
  },
  {
    "id": "getWorkbenchBootstrap",
    "method": "GET",
    "path": "/workbench/bootstrap"
  },
  {
    "id": "getWorkforceAdministrationSnapshot",
    "method": "GET",
    "path": "/workforce-administration"
  },
  {
    "id": "executeWorkforceAdministrationCommand",
    "method": "POST",
    "path": "/workforce-administration/commands"
  },
  {
    "id": "listWorkforceAccounts",
    "method": "GET",
    "path": "/workforce-administration/accounts"
  }
] as const;
