import { createHash } from "node:crypto";
import { Ajv2020, type ErrorObject, type ValidateFunction } from "ajv/dist/2020.js";
import { FormSchemaError } from "./errors.js";
import type { FormActor, FormUiSchema, JsonObject } from "./types.js";

const ID=/^[a-z][a-z0-9_.-]{0,127}$/u; const REF=/^[A-Za-z0-9_.:-]{1,255}$/u; const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/iu; const TRACE=/^(?!0{32})[0-9a-f]{32}$/u;
const SENSITIVE=/(credential|password|secret|session|token)/iu; const UNSAFE_TEXT=/(?:<|>|https?:\/\/|javascript:|data:)/iu;
const KEYWORDS=new Set(["$defs","$ref","$schema","additionalProperties","const","description","enum","format","items","maxItems","maxLength","maximum","minItems","minLength","minimum","properties","required","title","type"]);
const invalid=(code: "form_invalid_input"|"form_schema_rejected"="form_invalid_input"):never=>{throw new FormSchemaError(code)};
const object=(v:unknown):Record<string,unknown>=>typeof v==="object"&&v!==null&&!Array.isArray(v)?v as Record<string,unknown>:invalid();
const exact=(v:unknown,required:readonly string[],optional:readonly string[]=[]):Record<string,unknown>=>{const o=object(v);const keys=Object.keys(o);if(required.some(k=>!Object.hasOwn(o,k))||keys.some(k=>!required.includes(k)&&!optional.includes(k)))invalid();return o};
const array=(v:unknown,max:number):unknown[]=>{if(!Array.isArray(v)||v.length>max)invalid("form_schema_rejected");return v as unknown[]};
export const identifier=(v:unknown):string=>typeof v==="string"&&ID.test(v)?v:invalid();
export const uuid=(v:unknown):string=>typeof v==="string"&&UUID.test(v)?v.toLowerCase():invalid();
export const trace=(v:unknown):string=>typeof v==="string"&&TRACE.test(v)?v.toLowerCase():invalid();
export const boundedReason=(v:unknown):string=>typeof v==="string"&&v.length>=1&&v.length<=500?v:invalid();
export const positiveVersion=(v:unknown,allowZero=false):number=>Number.isSafeInteger(v)&&(v as number)>=(allowZero?0:1)?v as number:invalid();
export function actor(v:unknown):FormActor{const o=exact(v,["actorId","actorType"],["assignmentId"]);const actorType=o.actorType==="authenticated_subject"||o.actorType==="system"?o.actorType:invalid();return{actorId:typeof o.actorId==="string"&&REF.test(o.actorId)?o.actorId:invalid(),actorType,...(o.assignmentId===undefined?{}:{assignmentId:uuid(o.assignmentId)})}}
export function command(v:unknown,fields:readonly string[]):{readonly actor:FormActor;readonly operationId:string;readonly reason:string;readonly traceId:string;readonly values:Record<string,unknown>}{const values=exact(v,["actor","operationId","reason","traceId",...fields]);return{actor:actor(values.actor),operationId:uuid(values.operationId),reason:boundedReason(values.reason),traceId:trace(values.traceId),values}}
export function read(v:unknown,withData=false):{readonly actor:FormActor;readonly data?:unknown;readonly definitionId:string;readonly releaseVersion:number}{const o=exact(v,withData?["actor","data","definitionId","releaseVersion"]:["actor","definitionId","releaseVersion"]);return{actor:actor(o.actor),...(withData?{data:o.data}:{}),definitionId:identifier(o.definitionId),releaseVersion:positiveVersion(o.releaseVersion)}}
export function decision(v:unknown):{readonly allowed:boolean;readonly decisionId:string}{const o=exact(v,["allowed","decisionId"]);const allowed=typeof o.allowed==="boolean"?o.allowed:invalid();return{allowed,decisionId:uuid(o.decisionId)}}

const scalar=(v:unknown):boolean=>v===null||typeof v==="string"||typeof v==="boolean"||(typeof v==="number"&&Number.isFinite(v));
function inspectSchema(v:unknown,depth=0):void{if(depth>12)invalid("form_schema_rejected");const o=object(v);for(const key of Object.keys(o)){if(!KEYWORDS.has(key))invalid("form_schema_rejected");const value=o[key];if((key==="title"||key==="description")&&(typeof value!=="string"||value.length>500||UNSAFE_TEXT.test(value)))invalid("form_schema_rejected");if(key==="$ref"&&(typeof value!=="string"||!value.startsWith("#/$defs/")||value.includes("..")))invalid("form_schema_rejected");if(key==="format"&&value!=="date"&&value!=="date-time")invalid("form_schema_rejected");if(key==="properties"||key==="$defs"){const entries=Object.entries(object(value));if(entries.length>100)invalid("form_schema_rejected");for(const[name,child]of entries){if(!ID.test(name)||SENSITIVE.test(name))invalid("form_schema_rejected");inspectSchema(child,depth+1)}}else if(key==="items")inspectSchema(value,depth+1);else if(key==="required"){if(!Array.isArray(value)||value.some(x=>typeof x!=="string"||!ID.test(x))||new Set(value).size!==value.length)invalid("form_schema_rejected")}else if(key==="enum"){if(!Array.isArray(value)||value.length>100||value.some(x=>!scalar(x)))invalid("form_schema_rejected")}}}
export function schema(v:unknown):JsonObject{const size=Buffer.byteLength(JSON.stringify(v),"utf8");if(size>65_536)invalid("form_schema_rejected");inspectSchema(v);const o=object(v);if(o.$schema!=="https://json-schema.org/draft/2020-12/schema"||o.type!=="object"||o.additionalProperties!==false)invalid("form_schema_rejected");return structuredClone(o)}
export function ui(v:unknown,jsonSchema:JsonObject):FormUiSchema{const o=exact(v,["fields","layout","version"]);const layout=o.layout==="grid"||o.layout==="vertical"?o.layout:invalid("form_schema_rejected");if(o.version!==1)invalid("form_schema_rejected");const properties=object(jsonSchema.properties);const names=new Set<string>();const fields=array(o.fields,100).map(candidate=>{const f=exact(candidate,["component","field","order"],["span"]);const field=identifier(f.field);if(names.has(field)||!Object.hasOwn(properties,field))invalid("form_schema_rejected");names.add(field);const component=["date","input","number","select","switch","textarea"].includes(String(f.component))?f.component as FormUiSchema["fields"][number]["component"]:invalid("form_schema_rejected");const order=Number.isSafeInteger(f.order)&&(f.order as number)>=0&&(f.order as number)<=100000?f.order as number:invalid("form_schema_rejected");const span=f.span===undefined?undefined:Number.isSafeInteger(f.span)&&(f.span as number)>=1&&(f.span as number)<=24?f.span as number:invalid("form_schema_rejected");return{component,field,order,...(span===undefined?{}:{span})}});return{fields,layout,version:1}}
const leapYear=(year:number):boolean=>year%4===0&&(year%100!==0||year%400===0);
const validDateParts=(year:number,month:number,day:number):boolean=>{const maximum=[31,leapYear(year)?29:28,31,30,31,30,31,31,30,31,30,31][month-1];return maximum!==undefined&&day>=1&&day<=maximum};
const strictDate=(value:string):boolean=>{const match=/^(\d{4})-(\d{2})-(\d{2})$/u.exec(value);return match!==null&&validDateParts(Number(match[1]),Number(match[2]),Number(match[3]))};
const strictDateTime=(value:string):boolean=>{const match=/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})(?:\.\d{3})?Z$/u.exec(value);return match!==null&&validDateParts(Number(match[1]),Number(match[2]),Number(match[3]))&&Number(match[4])<=23&&Number(match[5])<=59&&Number(match[6])<=59};
export function compileSchema(value:JsonObject):ValidateFunction{try{const ajv=new Ajv2020({allErrors:true,strict:true});ajv.addFormat("date",{type:"string",validate:strictDate});ajv.addFormat("date-time",{type:"string",validate:strictDateTime});return ajv.compile(value)}catch(error){throw new FormSchemaError("form_schema_rejected",{cause:error})}}
export const safeErrors=(errors:readonly ErrorObject[]|null|undefined):readonly{instancePath:string;keyword:string}[]=>(errors??[]).slice(0,100).map(({instancePath,keyword})=>({instancePath,keyword}));
const canonical=(v:unknown):string=>Array.isArray(v)?`[${v.map(canonical).join(",")}]`:typeof v==="object"&&v!==null?`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonical((v as Record<string,unknown>)[k])}`).join(",")}}`:JSON.stringify(v);
export const digest=(jsonSchema:JsonObject,uiSchema:FormUiSchema):string=>createHash("sha256").update(canonical({jsonSchema,uiSchema})).digest("hex");
export const fingerprint=(v:unknown):string=>createHash("sha256").update(canonical(v)).digest("hex");
